import {
  aspectsBarbarian,
  aspectsFilterBarbarian,
  aspectsRightBarbarian,
  gearLeftBarbarian,
  gearRightBarbarian,
  gemsBarbarian,
  GemsOptionsBarbarian,
  itemStateBarbarian,
  optionSkillsBarbarian,
  optionSParagonBarbarian,
  optiontechsBarbarian,
  skillsBarbarian,
  techniquesBarbarian,
} from "./barbarian";
import {
  aspectsSpiritborn,
  aspectsFilterSpiritborn,
  aspectsRightSpiritborn,
  gearLeftSpiritborn,
  gearRightSpiritborn,
  gemsSpiritborn,
  GemsOptionsSpiritborn,
  itemStateSpiritborn,
  optionSkillsSpiritborn,
  optionSParagonSpiritborn,
  optiontechsSpiritborn,
  skillsSpiritborn,
  techniquesSpiritborn,
} from "./spiritborn";
import {
  aspectsDruid,
  aspectsFilterDruid,
  aspectsRightDruid,
  gearLeftDruid,
  gearRightDruid,
  gemsDruid,
  GemsOptionsDruid,
  itemStateDruid,
  optionSkillsDruid,
  optionSParagonDruid,
  optiontechsDruid,
  skillsDruid,
  techniquesDruid,
} from "./druid";
import {
  aspectsSorcerer,
  aspectsFilterSorcerer,
  aspectsRightSorcerer,
  gearLeftSorcerer,
  gearRightSorcerer,
  gemsSorcerer,
  GemsOptionsSorcerer,
  itemStateSorcerer,
  optionSkillsSorcerer,
  optionSParagonSorcerer,
  optiontechsSorcerer,
  skillsSorcerer,
  techniquesSorcerer,
} from "./sorcerer";
import {
  aspectsRogue,
  aspectsFilterRogue,
  aspectsRightRogue,
  gearLeftRogue,
  gearRightRogue,
  gemsRouge,
  GemsOptionsRogue,
  itemStateRogue,
  optionSkillsRogue,
  optionSParagonRogue,
  optiontechsRogue,
  skillsRogue,
  techniquesRogue,
} from "./rogue";
import {
  aspectsNecromancer,
  aspectsFilterNecromancer,
  aspectsRightNecromancer,
  gearLeftNecromancer,
  gearRightNecromancer,
  gemsNecromancer,
  GemsOptionsNecromancer,
  itemStateNecromancer,
  optionSkillsNecromancer,
  optionSParagonNecromancer,
  optiontechsNecromancer,
  skillsNecromancer,
  techniquesNecromancer,
} from "./necromancer";

export const siteTitle = "Next.js Starter Blog";

export const navbarLinks = [
  { route: "/about-us", label: "À propos" },
  { route: "/pricing", label: "Tarification" },
  { route: "/privacy-policy", label: "Politiques" },
  { route: "/contact-us", label: "Contactez-nous" },
];

export const navigationLinks = [
  { route: "/", label: "Méta Builds" },
  { route: "/my-builds", label: "Mes Builds" },
  { route: "/build-planner", label: "Planificateur de Build" },
];

export const footerLinks = [
  { route: "/about-us", label: "À propos" },
  { route: "/privacy-policy", label: "Politiques" },
  { route: "/contact-us", label: "Contactez-nous" },
];

export const socialLinks = [
  { route: "https://x.com/vercel", label: "Twitter" },
  { route: "https://linkedin.com/in/vercel", label: "LinkedIn" },
];

export const seasons = [
  { value: "Season 8", label: "Saison 8" },
  { value: "Season 9", label: "Saison 9" },
];

export const categories = [
  {
    value: "barbarian",
    label: "Barbare",
    bg: "bg-[#311e1d]",
    image: "barbarian.png",
    description: "Calculateur de planification de construction pour Diablo 4",
  },
  {
    value: "druid",
    label: "Druide",
    bg: "bg-[#392c1d]",
    image: "druid.png",
    description: "Calculateur de planification de construction pour Diablo 4",
  },
  {
    value: "necromancer",
    label: "Nécromancien",
    bg: "bg-[#173533]",
    image: "necromancer.png",
    description: "Calculateur de planification de construction pour Diablo 4",
  },
  {
    value: "rogue",
    label: "Voleur",
    bg: "bg-[#261e31]",
    image: "rogue.png",
    description: "Calculateur de planification de construction pour Diablo 4",
  },
  {
    value: "sorcerer",
    label: "Sorcier",
    bg: "bg-[#17283b]",
    image: "sorcerer.png",
    description: "Calculateur de planification de construction pour Diablo 4",
  },
  {
    value: "spiritborn",
    label: "Spiritborn",
    bg: "bg-[#17283b]",
    image: "sorcerer.png",
    description: "Calculateur de planification de construction pour Diablo 4",
  },
];

export const glyphs = [
  {
    id: 1,
    label: "Ambidextrous",
    image: "/paragon/barbarian/glyph1.png",
    code: "Glyph",
    radius: 3,
    effects: ["Rare Glyph"],
  },
  {
    id: 2,
    label: "Bloodfeeder",
    image: "/paragon/barbarian/glyph2.png",
    code: "Glyph",
    radius: 3,
    effects: ["Rare Glyph"],
  },
  {
    id: 3,
    label: "Brawl",
    image: "/paragon/barbarian/glyph3.png",
    code: "Glyph",
    radius: 3,
    effects: ["Rare Glyph"],
  },
  {
    id: 4,
    label: "Challenger",
    image: "/paragon/barbarian/glyph4.png",
    code: "Glyph",
    radius: 3,
    effects: ["Rare Glyph"],
  },
  {
    id: 5,
    label: "Cleaver",
    image: "/paragon/barbarian/glyph5.png",
    code: "Glyph",
    radius: 3,
    effects: ["Rare Glyph"],
  },
  {
    id: 6,
    label: "Crusher",
    image: "/paragon/barbarian/glyph6.png",
    code: "Glyph",
    radius: 3,
    effects: ["Rare Glyph"],
  },
];

export const data = {
  barbarian: {
    gearLeft: gearLeftBarbarian,
    gearRight: gearRightBarbarian,
    gems: gemsBarbarian,
    gemsOptions: GemsOptionsBarbarian,
    aspects: aspectsBarbarian,
    aspectsRight: aspectsRightBarbarian,
    aspectsFilter: aspectsFilterBarbarian,
    itemState: itemStateBarbarian,
    skills: skillsBarbarian,
    optiontechs: optiontechsBarbarian,
    techniques: techniquesBarbarian,
    optionSkills: optionSkillsBarbarian,
    paragon_builds: optionSParagonBarbarian,
    glyphs: glyphs,
  },
  spiritborn: {
    gearLeft: gearLeftSpiritborn,
    gearRight: gearRightSpiritborn,
    gems: gemsSpiritborn,
    gemsOptions: GemsOptionsSpiritborn,
    aspects: aspectsSpiritborn,
    aspectsRight: aspectsRightSpiritborn,
    aspectsFilter: aspectsFilterSpiritborn,
    itemState: itemStateSpiritborn,
    skills: skillsSpiritborn,
    optiontechs: optiontechsSpiritborn,
    techniques: techniquesSpiritborn,
    optionSkills: optionSkillsSpiritborn,
    paragon_builds: optionSParagonSpiritborn,
    glyphs: glyphs,
  },
  druid: {
    gearLeft: gearLeftDruid,
    gearRight: gearRightDruid,
    gems: gemsDruid,
    gemsOptions: GemsOptionsDruid,
    aspects: aspectsDruid,
    aspectsRight: aspectsRightDruid,
    aspectsFilter: aspectsFilterDruid,
    itemState: itemStateDruid,
    skills: skillsDruid,
    optiontechs: optiontechsDruid,
    techniques: techniquesDruid,
    optionSkills: optionSkillsDruid,
    paragon_builds: optionSParagonDruid,
    glyphs: glyphs,
  },
  necromancer: {
    gearLeft: gearLeftNecromancer,
    gearRight: gearRightNecromancer,
    gems: gemsNecromancer,
    gemsOptions: GemsOptionsNecromancer,
    aspects: aspectsNecromancer,
    aspectsRight: aspectsRightNecromancer,
    aspectsFilter: aspectsFilterNecromancer,
    itemState: itemStateNecromancer,
    skills: skillsNecromancer,
    optiontechs: optiontechsNecromancer,
    techniques: techniquesNecromancer,
    optionSkills: optionSkillsNecromancer,
    paragon_builds: optionSParagonNecromancer,
    glyphs: glyphs,
  },
  rogue: {
    gearLeft: gearLeftRogue,
    gearRight: gearRightRogue,
    gems: gemsRouge,
    gemsOptions: GemsOptionsRogue,
    aspects: aspectsRogue,
    aspectsRight: aspectsRightRogue,
    aspectsFilter: aspectsFilterRogue,
    itemState: itemStateRogue,
    skills: skillsRogue,
    optiontechs: optiontechsRogue,
    techniques: techniquesRogue,
    optionSkills: optionSkillsRogue,
    paragon_builds: optionSParagonRogue,
    glyphs: glyphs,
  },
  sorcerer: {
    gearLeft: gearLeftSorcerer,
    gearRight: gearRightSorcerer,
    gems: gemsSorcerer,
    gemsOptions: GemsOptionsSorcerer,
    aspects: aspectsSorcerer,
    aspectsRight: aspectsRightSorcerer,
    aspectsFilter: aspectsFilterSorcerer,
    itemState: itemStateSorcerer,
    skills: skillsSorcerer,
    optiontechs: optiontechsSorcerer,
    techniques: techniquesSorcerer,
    optionSkills: optionSkillsSorcerer,
    paragon_builds: optionSParagonSorcerer,
    glyphs: glyphs,
  },
};

export const gearLeft = [
  {
    image: "/gears/helm.png",
    label: "Casque",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/chest_armor.png",
    label: "Armure de Torse",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/gloves.png",
    label: "Gants",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/pants.png",
    label: "Pantalon",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/boots.png",
    label: "Bottes",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/bludgeoning_weapon.png",
    label: "Arme Contondante",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/dual-wield_weapon_1.png",
    label: "Arme Double 1",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
];

export const gearRight = [
  {
    image: "empty.png",
    label: "",
    description: "",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/amulet.png",
    label: "Amulette",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/ring_1.png",
    label: "Anneau 1",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/ring_1.png",
    label: "Anneau 2",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "empty.png",
    label: "",
    description: "",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/slashing_weapon.png",
    label: "Arme Tranchante",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
  {
    image: "/gears/dual-wield_weapon_2.png",
    label: "Arme Double 2",
    description: "Vide",
    aspect_id: null,
    aspect_power_id: null,
    aspect_power_id_2: null,
    details: {
      selects1: [],
      selects2: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
      selects3: [
        { value: 0, selectedValue: "" },
        { value: 0, selectedValue: "" },
      ],
    },
  },
];

export const gems = [
  { image: "empty.png", label: "", option_id: null },
  { image: "empty.png", label: "", option_id: null },
  { image: "empty.png", label: "", option_id: null },
  { image: "empty.png", label: "", option_id: null },
  { image: "empty.png", label: "", option_id: null },
];

export const GemsOptions = [
  {
    id: 1,
    label: "Améthyste",
    image: "/gems/amethyst.png",
    code: "Gemme",
    options: [
      "Arme : +18 % de dégâts sur la durée",
      "Armure : 100 de force",
      "Bijoux : 45 % de résistance à l'ombre",
    ],
  },
  {
    id: 2,
    label: "Émeraude",
    image: "/gems/emerald.png",
    code: "Gemme",
    options: [
      "Arme : +25 % de dégâts de coup critique",
      "Armure : 100 de dextérité",
      "Bijoux : 45 % de résistance au poison",
    ],
  },
  {
    id: 3,
    label: "Rubis",
    image: "/gems/ruby.png",
    code: "Gemme",
    options: [
      "Arme : +54 % de dégâts de surpuissance",
      "Armure : 9 % de vie maximale",
      "Bijoux : 45 % de résistance au feu",
    ],
  },
  {
    id: 4,
    label: "Topaze",
    image: "/gems/topaz.png",
    code: "Gemme",
    options: [
      "Arme : +45 % de dégâts de compétence de base",
      "Armure : 100 d'intelligence",
      "Bijoux : 45 % de résistance à la foudre",
    ],
  },
  {
    id: 5,
    label: "Saphir",
    image: "/gems/sapphire.png",
    code: "Gemme",
    options: [
      "Arme : +20 % de dégâts de vulnérabilité",
      "Armure : 100 de volonté",
      "Bijoux : 45 % de résistance au froid",
    ],
  },
  {
    id: 6,
    label: "Diamant",
    image: "/gems/diamond.png",
    code: "Gemme",
    options: [
      "Arme : +35 % de dégâts ultimes",
      "Armure : +11 % de génération de barrière",
      "Bijoux : 8 % de résistance à tous les éléments",
    ],
  },
  {
    id: 7,
    label: "Crâne",
    image: "/gems/skull.png",
    code: "Gemme",
    options: [
      "Arme : +48 Vie par élimination",
      "Armure : +15% de soins reçus",
      "Bijoux : +525 Armure",
    ],
  },
];

export const aspects = [
  {
    id: 1,
    image: "/gears/anda.png",
    label: "Visage d'Andariel",
    description: "Casque Unique",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 1,
    image: "/gears/utility.png",
    label: "Aspect de l'Anémie",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 2,
    image: "/gears/utility.png",
    label: "Aspect de l'Anémie",
    category: "Offensive",
    allowedGear: ["Barre", "gloves"],
  },
  {
    id: 3,
    image: "/gears/utility.png",
    label: "Aspect de l'Assistance",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 4,
    image: "/gears/defensive.png",
    label: "Aspect de l'Audace",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 5,
    image: "/gears/utility.png",
    label: "Aspect de Bul-Kathos",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 6,
    image: "/gears/defensive.png",
    label: "Aspect des Frappe Concussives",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 7,
    image: "/gears/utility.png",
    label: "Aspect des Foulées Glaciales",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 8,
    image: "/gears/utility.png",
    label: "Aspect de la Saisie du Tourbillon",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 9,
    image: "/gears/defensive.png",
    label: "Aspect de la Puissance",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 10,
    image: "/gears/defensive.png",
    label: "Aspect de la Colère Engourdissante",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 11,
    image: "/gears/utility.png",
    label: "Aspect de la Misère Partagée",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 12,
    image: "/gears/defensive.png",
    label: "Aspect des Étapes Sournoises",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 13,
    image: "/gears/defensive.png",
    label: "Aspect des Coups Tempérés",

    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 14,
    image: "/gears/defensive.png",
    label: "Aspect de la Sagesse de la Foule",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 15,
    image: "/gears/defensive.png",
    label: "Aspect de la Barrière Défléchissante",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 16,
    image: "/gears/defensive.png",
    label: "Aspect de la Forteresse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 17,
    image: "/gears/defensive.png",
    label: "Aspect du Guerrier de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 18,
    image: "/gears/defensive.png",
    label: "Aspect du Protecteur",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 19,
    image: "/gears/defensive.png",
    label: "Aspect du Cœur Prudent",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 20,
    image: "/gears/defensive.png",
    label: "Aspect de l'Assimilation",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 21,
    image: "/gears/crown.png",
    label: "Couronne de Lucienne",
    description: "Casque Unique",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 22,
    image: "/gears/utility.png",
    label: "Aspect Évasif",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 23,
    image: "/gears/godslayer_crown.png",
    label: "Couronne de l'Anéantisseur",
    description: "Casque Unique",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 24,
    image: "/gears/harlequin_crest.png",
    label: "Crête d'Arlequin",
    description: "Casque Unique",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 25,
    image: "/gears/utility.png",
    label: "Aspect Hectique",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 26,
    image: "/gears/tuskhelm_of_joritz_the_mighty.png",
    label: "Héritier de la Perdition",
    description: "Casque Unique",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 27,
    image: "/gears/defensive.png",
    label: "Aspect du Sang de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 28,
    image: "/gears/defensive.png",
    label: "Aspect du Colosse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 29,
    image: "/gears/utility.png",
    label: "Aspect de Porte-Bonheur",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 30,
    image: "/gears/defensive.png",
    label: "Aspect de Protection",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 31,
    image: "/gears/utility.png",
    label: "Aspect du Berserker Relentless",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 32,
    image: "/gears/defensive.png",
    label: "Aspect du Berserker Steadfast",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 33,
    image: "/gears/utility.png",
    label: "Aspect de Réflexion Rapide",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 34,
    image: "/gears/tuskhelm_of_joritz_the_mighty.png",
    label: "Tuskhelm de Joritz le Puissant",
    description: "Casque Unique",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 35,
    image: "/gears/ugly_bastard_helm.png",
    label: "Casque du Bâtard Laid",
    description: "Casque Unique",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 36,
    image: "/gears/defensive.png",
    label: "Aspect Immortel",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 37,
    image: "/gears/utility.png",
    label: "Aspect du Maître des Armes",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  {
    id: 38,
    image: "/gears/utility.png",
    label: "Aspect Sauvage",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Barre"],
  },
  // Armure de poitrine
  {
    id: 39,
    image: "/gears/utility.png",
    label: "Aspect de l'Anémie",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 40,
    image: "/gears/utility.png",
    label: "Aspect de l'Assistance",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 41,
    image: "/gears/utility.png",
    label: "Aspect de l'Audace",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 42,
    image: "/gears/defensive.png",
    label: "Aspect de Bul-Kathos",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 43,
    image: "/gears/utility.png",
    label: "Aspect des Frappe Concussives",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 44,
    image: "/gears/defensive.png",
    label: "Aspect de la Désobéissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 45,
    image: "/gears/utility.png",
    label: "Aspect des Foulées Glaciales",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 46,
    image: "/gears/utility.png",
    label: "Aspect de la Saisie du Tourbillon",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 47,
    image: "/gears/defensive.png",
    label: "Aspect de la Puissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 48,
    image: "/gears/defensive.png",
    label: "Aspect de la Colère Engourdissante",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 49,
    image: "/gears/utility.png",
    label: "Aspect du Tourbillon Saisissant",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 50,
    image: "/gears/defensive.png",
    label: "Aspect de la Sagesse de la Foule",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 51,
    image: "/gears/defensive.png",
    label: "Aspect de la Barrière Défléchissante",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 52,
    image: "/gears/defensive.png",
    label: "Aspect de la Forteresse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 53,
    image: "/gears/defensive.png",
    label: "Aspect du Guerrier de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 54,
    image: "/gears/defensive.png",
    label: "Aspect du Protecteur",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 55,
    image: "/gears/defensive.png",
    label: "Aspect du Cœur Prudent",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 56,
    image: "/gears/defensive.png",
    label: "Aspect de l'Assimilation",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 57,
    image: "/gears/defensive.png",
    label: "Aspect Évasif",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 58,
    image: "/gears/defensive.png",
    label: "Aspect Hectique",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 59,
    image: "/gears/utility.png",
    label: "Aspect du Sang de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 60,
    image: "/gears/utility.png",
    label: "Aspect du Colosse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 61,
    image: "/gears/defensive.png",
    label: "Aspect de Porte-Bonheur",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 62,
    image: "/gears/defensive.png",
    label: "Aspect de Protection",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 63,
    image: "/gears/utility.png",
    label: "Aspect du Berserker Relentless",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 64,
    image: "/gears/mantle_of_mountain's_fury.png",
    label: "Aspect du Berserker Steadfast",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 65,
    image: "/gears/defensive.png",
    label: "Aspect de Réflexion Rapide",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 66,
    image: "/gears/mantle_of_mountain's_fury.png",
    label: "Aspect Immortel",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 67,
    image: "/gears/razorplate.png",
    label: "Aspect du Maître des Armes",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 68,
    image: "/gears/utility.png",
    label: "Aspect Sauvage",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 69,
    image: "/gears/shroud_of_false_death.png",
    label: "Aspect du Tourbillon Saisissant",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 70,
    image: "/gears/soulbrand.png",
    label: "Aspect de la Puissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 71,
    image: "/gears/defensive.png",
    label: "Aspect de la Misère Partagée",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 72,
    image: "/gears/utility.png",
    label: "Aspect des Étapes Sournoises",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 73,
    image: "/gears/tyrael's_might.png",
    label: "Aspect des Coups Tempérés",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 74,
    image: "/gears/defensive.png",
    label: "Aspect du Tourbillon Embrasé",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 75,
    image: "/gears/utility.png",
    label: "Aspect de la Sagesse de la Foule",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  {
    id: 76,
    image: "/gears/utility.png",
    label: "Aspect Évasif",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Armure de poitrine"],
  },
  // gloves
  {
    id: 77,
    image: "/gears/offensive.png",
    label: "Aspect de l'Anémie",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 78,
    image: "/gears/offensive.png",
    label: "Aspect de l'Assistance",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 79,
    image: "/gears/offensive.png",
    label: "Aspect de l'Audace",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 80,
    image: "/gears/offensive.png",
    label: "Aspect de Bul-Kathos",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 81,
    image: "/gears/offensive.png",
    label: "Aspect des Coups Concussifs",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 82,
    image: "/gears/utility.png",
    label: "Aspect de la Désobéissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 83,
    image: "/gears/offensive.png",
    label: "Aspect des Pas Glaciaux",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 84,
    image: "/gears/offensive.png",
    label: "Aspect de la Saisie du Tourbillon",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 85,
    image: "/gears/utility.png",
    label: "Aspect de la Puissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 86,
    image: "/gears/utility.png",
    label: "Aspect de la Colère Engourdissante",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 87,
    image: "/gears/offensive.png",
    label: "Aspect du Tourbillon Saisissant",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 88,
    image: "/gears/offensive.png",
    label: "Aspect de la Sagesse de la Foule",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 89,
    image: "/gears/utility.png",
    label: "Aspect de la Barrière Défléchissante",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 90,
    image: "/gears/offensive.png",
    label: "Aspect de la Forteresse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 91,
    image: "/gears/offensive.png",
    label: "Aspect du Guerrier de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 92,
    image: "/gears/offensive.png",
    label: "Aspect du Protecteur",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 93,
    image: "/gears/offensive.png",
    label: "Aspect du Cœur Prudent",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 94,
    image: "/gears/offensive.png",
    label: "Aspect de l'Assimilation",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 95,
    image: "/gears/offensive.png",
    label: "Aspect Évasif",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 96,
    image: "/gears/utility.png",
    label: "Aspect Hectique",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 97,
    image: "/gears/utility.png",
    label: "Aspect du Sang de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 98,
    image: "/gears/offensive.png",
    label: "Aspect du Colosse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 99,
    image: "/gears/offensive.png",
    label: "Aspect de Porte-Bonheur",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 100,
    image: "/gears/offensive.png",
    label: "Aspect de Protection",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 101,
    image: "/gears/offensive.png",
    label: "Aspect du Berserker Relentless",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 102,
    image: "/gears/offensive.png",
    label: "Aspect du Berserker Steadfast",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 103,
    image: "/gears/offensive.png",
    label: "Aspect de Réflexion Rapide",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 104,
    image: "/gears/utility.png",
    label: "Aspect Immortel",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 105,
    image: "/gears/offensive.png",
    label: "Aspect du Maître des Armes",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 106,
    image: "/gears/offensive.png",
    label: "Aspect Sauvage",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 107,
    image: "/gears/offensive.png",
    label: "Aspect du Tourbillon Saisissant",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 108,
    image: "/gears/offensive.png",
    label: "Aspect de la Puissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 109,
    image: "/gears/offensive.png",
    label: "Aspect de la Misère Partagée",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 110,
    image: "/gears/offensive.png",
    label: "Aspect des Pas Sournois",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 111,
    image: "/gears/bane_of_ahjed-den.png",
    label: "Aspect des Coups Tempérés",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 112,
    image: "/gears/offensive.png",
    label: "Aspect du Tourbillon Enflammé",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 113,
    image: "/gears/offensive.png",
    label: "Aspect de la Sagesse de la Foule",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 114,
    image: "/gears/offensive.png",
    label: "Aspect Évasif",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 115,
    image: "/gears/offensive.png",
    label: "Aspect du Maître des Armes",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 116,
    image: "/gears/offensive.png",
    label: "Aspect Sauvage",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 117,
    image: "/gears/offensive.png",
    label: "Aspect de la Colère Engourdissante",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 118,
    image: "/gears/offensive.png",
    label: "Aspect du Guerrier de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 119,
    image: "/gears/offensive.png",
    label: "Aspect de la Forteresse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 120,
    image: "/gears/offensive.png",
    label: "Aspect des Coups Concussifs",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 121,
    image: "/gears/utility.png",
    label: "Aspect de l'Assimilation",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 122,
    image: "/gears/endurant_faith.png",
    label: "Aspect du Protecteur",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 123,
    image: "/gears/Offensive.png",
    label: "Aspect des Pas Glaciaux",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 124,
    image: "/gears/Offensive.png",
    label: "Aspect de la Désobéissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 125,
    image: "/gears/fists_of_fate.png",
    label: "Aspect de l'Audace",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 126,
    image: "/gears/frostburn.png",
    label: "Aspect de Bul-Kathos",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 127,
    image: "/gears/gohr's_devastating_grips.png",
    label: "Aspect de la Misère Partagée",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 128,
    image: "/gears/utility.png",
    label: "Aspect des Pas Sournois",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 129,
    image: "/gears/utility.png",
    label: "Aspect des Coups Tempérés",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 130,
    image: "/gears/Offensive.png",
    label: "Aspect du Tourbillon Enflammé",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 131,
    image: "/gears/paingorger's_gauntlets.png",
    label: "Aspect du Cœur Prudent",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 132,
    image: "/gears/Offensive.png",
    label: "Aspect du Berserker Relentless",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 133,
    image: "/gears/utility.png",
    label: "Aspect du Berserker Steadfast",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 134,
    image: "/gears/Offensive.png",
    label: "Aspect de Réflexion Rapide",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 135,
    image: "/gears/Offensive.png",
    label: "Aspect Immortel",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 136,
    image: "/gears/utility.png",
    label: "Aspect de Porte-Bonheur",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 137,
    image: "/gears/twin_strikes.png",
    label: "Aspect du Sang de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 138,
    image: "/gears/Offensive.png",
    label: "Aspect du Colosse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 139,
    image: "/gears/Offensive.png",
    label: "Aspect Hectique",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 140,
    image: "/gears/Offensive.png",
    label: "Aspect de Protection",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 141,
    image: "/gears/utility.png",
    label: "Aspect de la Colère Engourdissante",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 142,
    image: "/gears/utility.png",
    label: "Aspect de la Barrière Défléchissante",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  {
    id: 143,
    image: "/gears/Offensive.png",
    label: "Aspect de l'Anémie",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Gloves"],
  },
  // Pantalon
  {
    id: 77,
    image: "/gears/arreat's_bearing.png",
    label: "Aspect de l'Anémie",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 78,
    image: "/gears/utility.png",
    label: "Aspect de l'Assistance",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 79,
    image: "/gears/utility.png",
    label: "Aspect de l'Audace",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 80,
    image: "/gears/utility.png",
    label: "Aspect de Bul-Kathos",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 81,
    image: "/gears/defensive.png",
    label: "Aspect des Coups Concussifs",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 82,
    image: "/gears/utility.png",
    label: "Aspect de la Désobéissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 83,
    image: "/gears/defensive.png",
    label: "Aspect des Pas Glaciaux",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 84,
    image: "/gears/utility.png",
    label: "Aspect de la Saisie du Tourbillon",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 85,
    image: "/gears/utility.png",
    label: "Aspect de la Puissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 86,
    image: "/gears/defensive.png",
    label: "Aspect de la Colère Engourdissante",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 87,
    image: "/gears/defensive.png",
    label: "Aspect du Tourbillon Saisissant",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 88,
    image: "/gears/utility.png",
    label: "Aspect de la Sagesse de la Foule",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 89,
    image: "/gears/defensive.png",
    label: "Aspect de la Barrière Défléchissante",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 90,
    image: "/gears/defensive.png",
    label: "Aspect de la Forteresse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 91,
    image: "/gears/defensive.png",
    label: "Aspect du Guerrier de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 92,
    image: "/gears/defensive.png",
    label: "Aspect du Protecteur",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 93,
    image: "/gears/defensive.png",
    label: "Aspect du Cœur Prudent",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 94,
    image: "/gears/defensive.png",
    label: "Aspect de l'Assimilation",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 95,
    image: "/gears/defensive.png",
    label: "Aspect Évasif",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 96,
    image: "/gears/defensive.png",
    label: "Aspect Hectique",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 97,
    image: "/gears/defensive.png",
    label: "Aspect du Sang de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 98,
    image: "/gears/utility.png",
    label: "Aspect du Colosse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 99,
    image: "/gears/utility.png",
    label: "Aspect de Porte-Bonheur",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 100,
    image: "/gears/defensive.png",
    label: "Aspect de Protection",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 101,
    image: "/gears/defensive.png",
    label: "Aspect du Berserker Relentless",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 102,
    image: "/gears/utility.png",
    label: "Aspect du Berserker Steadfast",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 103,
    image: "/gears/defensive.png",
    label: "Aspect de Réflexion Rapide",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 104,
    image: "/gears/utility.png",
    label: "Aspect Immortel",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 105,
    image: "/gears/defensive.png",
    label: "Aspect du Maître des Armes",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 106,
    image: "/gears/utility.png",
    label: "Aspect Sauvage",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 107,
    image: "/gears/tassets_of_the_dawning_sky.png",
    label: "Aspect du Tourbillon Saisissant",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 108,
    image: "/gears/temerity.png",
    label: "Aspect de la Puissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 109,
    image: "/gears/tassets_of_the_dawning_sky.png",
    label: "Aspect de la Misère Partagée",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 110,
    image: "/gears/defensive.png",
    label: "Aspect des Pas Sournois",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 111,
    image: "/gears/utility.png",
    label: "Aspect des Coups Tempérés",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  {
    id: 111,
    image: "/gears/utility.png",
    label: "Aspect des Tempérés",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Pantalon"],
  },
  // Bottes
  {
    id: 77,
    image: "/gears/100,000_steps.png",
    label: "Aspect de l'Anémie",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 78,
    image: "/gears/utility.png",
    label: "Aspect de l'Assistance",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 79,
    image: "/gears/utility.png",
    label: "Aspect de l'Audace",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 80,
    image: "/gears/utility.png",
    label: "Aspect de Bul-Kathos",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 81,
    image: "/gears/utility.png",
    label: "Aspect des Coups Concussifs",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 82,
    image: "/gears/mobility.png",
    label: "Aspect de la Désobéissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 83,
    image: "/gears/utility.png",
    label: "Aspect des Pas Glaciaux",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 84,
    image: "/gears/utility.png",
    label: "Aspect de la Saisie du Tourbillon",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 85,
    image: "/gears/mobility.png",
    label: "Aspect de la Puissance",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 86,
    image: "/gears/mobility.png",
    label: "Aspect de la Colère Engourdissante",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 87,
    image: "/gears/utility.png",
    label: "Aspect du Tourbillon Saisissant",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 88,
    image: "/gears/mobility.png",
    label: "Aspect de la Sagesse de la Foule",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 89,
    image: "/gears/mobility.png",
    label: "Aspect de la Barrière Défléchissante",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 90,
    image: "/gears/utility.png",
    label: "Aspect de la Forteresse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 91,
    image: "/gears/flickerstep.png",
    label: "Aspect du Guerrier de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 92,
    image: "/gears/mobility.png",
    label: "Aspect du Protecteur",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 93,
    image: "/gears/utility.png",
    label: "Aspect du Cœur Prudent",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 94,
    image: "/gears/hooves_of_the_mountain_god.png",
    label: "Aspect de l'Assimilation",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 95,
    image: "/gears/utility.png",
    label: "Aspect Évasif",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 96,
    image: "/gears/penitent_greaves.png",
    label: "Aspect Hectique",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 97,
    image: "/gears/rakanoth's_wake.png",
    label: "Aspect du Sang de Fer",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 98,
    image: "/gears/utility.png",
    label: "Aspect du Colosse",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 99,
    image: "/gears/utility.png",
    label: "Aspect de Porte-Bonheur",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 100,
    image: "/gears/utility.png",
    label: "Aspect de Protection",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 101,
    image: "/gears/utility.png",
    label: "Aspect du Berserker Relentless",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 102,
    image: "/gears/mobility.png",
    label: "Aspect du Berserker Steadfast",
    description: "Légendaire Défensif",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  {
    id: 103,
    image: "/gears/yen's_blessing.png",
    label: "Aspect de Réflexion Rapide",
    description: "Légendaire d'Utilité",
    category: "Offensive",
    allowedGear: ["Bottes"],
  },
  // Bludgeonging Weapon
  {
    id: 1,
    image: "/gears/offensive.png",
    label: "Aspect d'Accélération",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 2,
    image: "/gears/offensive.png",
    label: "Aspect du Toucher Maudit",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 3,
    image: "/gears/offensive.png",
    label: "Aspect de la Charge Ancestrale",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 4,
    image: "/gears/offensive.png",
    label: "Aspect des Échos Ancestraux",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 5,
    image: "/gears/offensive.png",
    label: "Aspect de la Force Ancestrale",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 6,
    image: "/gears/offensive.png",
    label: "Aspect de la Gestion de la Colère",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 7,
    image: "/gears/offensive.png",
    label: "Aspect de la Furie Apogée",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 8,
    image: "/gears/offensive.png",
    label: "Aspect de l'Écorchement Berserk",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 9,
    image: "/gears/offensive.png",
    label: "Aspect de la Rage Ardente",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 10,
    image: "/gears/offensive.png",
    label: "Aspect de la Mort Rampante",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 11,
    image: "/gears/offensive.png",
    label: "Aspect de l'Extinction Retardée",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 12,
    image: "/gears/offensive.png",
    label: "Aspect des Tremblements de Terre",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 13,
    image: "/gears/offensive.png",
    label: "Aspect des Éléments",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 14,
    image: "/gears/offensive.png",
    label: "Aspect de la Colère Envahissante",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 15,
    image: "/gears/offensive.png",
    label: "Aspect des Vents Féroces",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 16,
    image: "/gears/offensive.png",
    label: "Aspect du Spectacle Herculean",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 17,
    image: "/gears/offensive.png",
    label: "Aspect des Fissures Incendiaires",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 18,
    image: "/gears/offensive.png",
    label: "Aspect du Destin Inévitable",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 19,
    image: "/gears/offensive.png",
    label: "Aspect du Calme Intérieur",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 20,
    image: "/gears/offensive.png",
    label: "Aspect de la Rage Illimitée",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 21,
    image: "/gears/offensive.png",
    label: "Aspect de la Rétribution",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 22,
    image: "/gears/offensive.png",
    label: "Aspect de l'Acier Brisé",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 23,
    image: "/gears/offensive.png",
    label: "Aspect du Sol Fendu",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 24,
    image: "/gears/offensive.png",
    label: "Aspect du Tourbillon Fatal",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 25,
    image: "/gears/offensive.png",
    label: "Aspect de l'Attente",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 26,
    image: "/gears/offensive.png",
    label: "Aspect de la Ruée Flamboyante",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 27,
    image: "/gears/offensive.png",
    label: "Aspect de l'Aube",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 28,
    image: "/gears/offensive.png",
    label: "Aspect de la Folie Combative",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 29,
    image: "/gears/offensive.png",
    label: "Aspect de l'Ébullition du Sang",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 30,
    image: "/gears/offensive.png",
    label: "Aspect du Combattant",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 31,
    image: "/gears/offensive.png",
    label: "Aspect de la Vanité",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 32,
    image: "/gears/offensive.png",
    label: "Aspect du Vœu de Mort",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 33,
    image: "/gears/offensive.png",
    label: "Aspect Démoniaque",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 34,
    image: "/gears/offensive.png",
    label: "Aspect du Diable de Poussière",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 35,
    image: "/gears/offensive.png",
    label: "Aspect du Frappeur Terrestre",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 36,
    image: "/gears/offensive.png",
    label: "Aspect du Maître de l'Arête",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 37,
    image: "/gears/offensive.png",
    label: "Aspect du Bourreau",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 38,
    image: "/gears/offensive.png",
    label: "Aspect de l'Exploiteur",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 39,
    image: "/gears/hellhammer.png",
    label: "Aspect de l'Éclat d'Aiguille",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 40,
    image: "/gears/offensive.png",
    label: "Aspect de Surcharge",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 41,
    image: "/gears/overkill.png",
    label: "Aspect Rapide",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 42,
    image: "/gears/offensive.png",
    label: "Aspect du Brise-Crâne",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 43,
    image: "/gears/offensive.png",
    label: "Aspect du Frappeur",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 44,
    image: "/gears/offensive.png",
    label: "Aspect du Combattant Vehement",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 45,
    image: "/gears/Offensive.png",
    label: "Aspect du Combattant Vétéran",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 46,
    image: "/gears/Offensive.png",
    label: "Aspect de la Rupture Déchaînée",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 47,
    image: "/gears/Offensive.png",
    label: "Aspect du Fouet de Vent",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  {
    id: 48,
    image: "/gears/Offensive.png",
    label: "Aspect de Vent",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Bludgeonging Weapon"],
  },
  // Arme à double usage 1
  {
    id: 1,
    image: "/gears/offensive.png",
    label: "Aspect d'Accélération",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 2,
    image: "/gears/offensive.png",
    label: "Aspect du Toucher Maudit",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 3,
    image: "/gears/offensive.png",
    label: "Aspect de la Charge Ancestrale",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 4,
    image: "/gears/offensive.png",
    label: "Aspect des Échos Ancestraux",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 5,
    image: "/gears/offensive.png",
    label: "Aspect de la Force Ancestrale",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 6,
    image: "/gears/offensive.png",
    label: "Aspect de la Gestion de la Colère",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 7,
    image: "/gears/offensive.png",
    label: "Aspect de la Furie Apogée",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 8,
    image: "/gears/offensive.png",
    label: "Aspect de l'Écorchement Berserk",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 9,
    image: "/gears/offensive.png",
    label: "Aspect de la Rage Ardente",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 10,
    image: "/gears/offensive.png",
    label: "Aspect de la Mort Rampante",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 11,
    image: "/gears/offensive.png",
    label: "Aspect de l'Extinction Retardée",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 12,
    image: "/gears/offensive.png",
    label: "Aspect des Tremblements de Terre",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 13,
    image: "/gears/offensive.png",
    label: "Aspect des Éléments",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 14,
    image: "/gears/offensive.png",
    label: "Aspect de la Colère Envahissante",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 15,
    image: "/gears/offensive.png",
    label: "Aspect des Vents Féroces",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 16,
    image: "/gears/offensive.png",
    label: "Aspect du Spectacle Herculean",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 17,
    image: "/gears/offensive.png",
    label: "Aspect des Fissures Incendiaires",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 18,
    image: "/gears/offensive.png",
    label: "Aspect du Destin Inévitable",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 19,
    image: "/gears/offensive.png",
    label: "Aspect du Calme Intérieur",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 20,
    image: "/gears/offensive.png",
    label: "Aspect de la Rage Illimitée",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 21,
    image: "/gears/offensive.png",
    label: "Aspect de la Rétribution",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 22,
    image: "/gears/offensive.png",
    label: "Aspect de l'Acier Brisé",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 23,
    image: "/gears/offensive.png",
    label: "Aspect du Sol Fendu",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 24,
    image: "/gears/offensive.png",
    label: "Aspect du Tourbillon Fatal",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 25,
    image: "/gears/offensive.png",
    label: "Aspect de l'Attente",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 26,
    image: "/gears/offensive.png",
    label: "Aspect de la Ruée Flamboyante",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 27,
    image: "/gears/offensive.png",
    label: "Aspect de l'Aube",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 28,
    image: "/gears/azurewrath.png",
    label: "Aspect de la Folie Combative",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 29,
    image: "/gears/offensive.png",
    label: "Aspect de l'Ébullition du Sang",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 30,
    image: "/gears/offensive.png",
    label: "Aspect du Combattant",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 31,
    image: "/gears/offensive.png",
    label: "Aspect de la Vanité",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 32,
    image: "/gears/offensive.png",
    label: "Aspect du Vœu de Mort",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 33,
    image: "/gears/offensive.png",
    label: "Aspect Démoniaque",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 34,
    image: "/gears/offensive.png",
    label: "Aspect du Diable de Poussière",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 35,
    image: "/gears/doombringer.png",
    label: "Aspect du Frappeur Terrestre",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 36,
    image: "/gears/offensive.png",
    label: "Aspect du Maître de l'Arête",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 37,
    image: "/gears/offensive.png",
    label: "Aspect du Bourreau",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 38,
    image: "/gears/offensive.png",
    label: "Aspect de l'Exploiteur",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 39,
    image: "/gears/offensive.png",
    label: "Aspect de l'Éclat d'Aiguille",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 40,
    image: "/gears/offensive.png",
    label: "Aspect de l'Œuvre Magnum de Ramaldini",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 41,
    image: "/gears/offensive.png",
    label: "Aspect Rapide",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 42,
    image: "/gears/ramaladni's_magnum_opus.png",
    label: "Aspect du Brise-Crâne",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 43,
    image: "/gears/offensive.png",
    label: "Aspect du Frappeur",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 44,
    image: "/gears/shard_of_verathiel.png",
    label: "Aspect du Combattant Vehement",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 45,
    image: "/gears/offensive.png",
    label: "Aspect du Combattant Vétéran",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 46,
    image: "/gears/offensive.png",
    label: "Aspect de la Rupture Déchaînée",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 47,
    image: "/gears/the_butcher's_cleaver.png",
    label: "Aspect du Fouet de Vent",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 48,
    image: "/gears/the_third_blade.png",
    label: "Éclat de Verathiel",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 49,
    image: "/gears/offensive.png",
    label: "Hache du Boucher",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 50,
    image: "/gears/offensive.png",
    label: "La Troisième Lame",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 51,
    image: "/gears/offensive.png",
    label: "Azurwrath",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
  {
    id: 52,
    image: "/gears/offensive.png",
    label: "Doombringer",
    description: "Légendaire Offensif",
    category: "Offensive",
    allowedGear: ["Arme à double usage 1"],
  },
];

export const aspectspower = [
  { id: 1, label: "Amethyst", image: "/gears/grand.png" },
  { id: 2, label: "emerald", image: "/gears/erald.png" },
  { id: 3, label: "Ruby", image: "/gears/ruby.png" },
  { id: 4, label: "Topaz", image: "/gears/graq.png" },
  { id: 5, label: "Sapphier", image: "/gears/gra.png" },
  { id: 6, label: "Diamand", image: "/gears/gran.png" },
];

const aspectsRight = [
  {
    id: 4,
    label: "Unique Ring of Starlight",
    category: "Unique",
    image: "/aspects/starlight.png",
    allowedGear: ["Ring"],
  },
  {
    id: 5,
    label: "Unique Amulet of Power",
    category: "Unique",
    image: "/aspects/power.png",
    allowedGear: ["Amulet"],
  },
  // Add more aspects for right-side gear
];

export const aspectsFilter = [
  {
    label: "Codex",
  },
  { label: "Drop-seulement" },
  {
    label: "Spécifique à la classe",
  },
  {
    label: "Unique",
  },
  {
    label: "Légendaire",
  },
  {
    label: "Offensif",
  },
  {
    label: "Défensive",
  },
  {
    label: "Mobilité",
  },
  {
    label: "Ressource",
  },
  {
    label: "Utilitaire",
  },
];

export const itemState = [
  {
    image: "/gears/charge.png",
    label: "Andariel's Visage",
    description: "Unique Helm",
    features: ["Unique", "Légendaire"],
  },
  {
    image: "/gears/charge.png",
    label: "Arme",
    description: "Description de l'Arme",
  },
  {
    image: "/gears/charge.png",
    label: "Arme",
    description: "Description de l'Arme",
  },
];

export const itemStateFooter = [
  {
    image: "/gears/charge.png",
    label: "Arme",
    description: "Description de l'Arme",
  },
  {
    image: "/gears/charge.png",
    label: "Arme",
    description: "Description de l'Arme",
  },
];

export const skills = [
  {
    image: "/skill-tech/empty_skill.png",
    parent_id: null,
    skill_id: null,
  },
  {
    image: "/skill-tech/empty_skill.png",
    parent_id: null,
    skill_id: null,
  },
  {
    image: "/skill-tech/empty_skill.png",
    parent_id: null,
    skill_id: null,
  },
  {
    image: "/skill-tech/empty_skill.png",
    parent_id: null,
    skill_id: null,
  },
  {
    image: "/skill-tech/empty_skill.png",
    parent_id: null,
    skill_id: null,
  },
  {
    image: "/skill-tech/empty_skill.png",
    parent_id: null,
    skill_id: null,
  },
];

export const techniques = [
  {
    image: "/skill-tech/empty_skill.png",
    option_id: null,
  },
];

export const optiontechs = [
  {
    image: "/skill-tech/1h_axe.png",
    id: 1,
    label: "Expertise Hache à Une Main",
    code: "Hache 1M",
    details:
      "+ [10.0%] de chance de coup critique contre les ennemis blessés. Double ce montant en utilisant deux haches.",
  },
  {
    image: "/skill-tech/1h_axe.png",
    id: 2,
    label: "Expertise Hache à Une Main",
    code: "Hache 1M",
    details:
      "+ [10.0%] de chance de coup critique contre les ennemis blessés. Double ce montant en utilisant deux haches.",
  },
  {
    image: "/skill-tech/1h_axe.png",
    id: 3,
    label: "Expertise Hache à Une Main",
    code: "Hache 1M",
    details:
      "+ [10.0%] de chance de coup critique contre les ennemis blessés. Double ce montant en utilisant deux haches.",
  },
  {
    image: "/skill-tech/1h_axe.png",
    id: 4,
    label: "Expertise Hache à Une Main",
    code: "Hache 1M",
    details:
      "+ [10.0%] de chance de coup critique contre les ennemis blessés. Double ce montant en utilisant deux haches.",
  },
  {
    image: "/skill-tech/1h_axe.png",
    id: 5,
    label: "Expertise Hache à Une Main",
    code: "Hache 1M",
    details:
      "+ [10.0%] de chance de coup critique contre les ennemis blessés. Double ce montant en utilisant deux haches.",
  },
  {
    image: "/skill-tech/1h_axe.png",
    id: 6,
    label: "Expertise Hache à Une Main",
    code: "Hache 1M",
    details:
      "+ [10.0%] de chance de coup critique contre les ennemis blessés. Double ce montant en utilisant deux haches.",
  },
];

export const optionSkills = [
  {
    image: "/skill-tech/category_basic.png",
    id: 1,
    next_id: 2,
    label: "Base",
    top: "9.16945%",
    left: "47.4826%",
    options: [
      {
        id: 1,
        image: "/skill-tech/bash.png",
        label: "Coup",
        details: [
          "Génération de Furie : 15",
          "Coup de Chance : 50% ",
          "<span class='text-gray-500'>Frappez l'ennemi avec votre arme, infligeant <span class='text-yellow-500'>[33%]</span> de dégâts. Après avoir frappé les ennemis 4 fois, votre prochain Coup les étourdira pendant 1,25 secondes, passant à 2 secondes si vous utilisez une arme à deux mains.</span>",
        ],
        footer: "Dégâts Physiques",
      },
      {
        id: 2,
        image: "/skill-tech/flay.png",
        label: "Écorcher",
        details: [
          "Génération de Furie : 15",
          "Coup de Chance : 50% ",
          "<span class='text-gray-500'>Écorchez l'ennemi, infligeant <span class='text-yellow-500'>[5%]</span> de dégâts et infligeant <span class='text-yellow-500'>[44%]</span> de dégâts de Saignement sur 5 secondes.</span>",
        ],
        footer: "Dégâts Physiques <br/> Nécessite une arme tranchante",
      },
      {
        id: 3,
        image: "/skill-tech/frenzy.png",
        label: "Frénésie",
        details: [
          "Génération de Furie : 4",
          "Coup de Chance : 30% ",
          "<span class='text-gray-500'>Déchaînez une rafale rapide de coups, infligeant <span class='text-yellow-500'>[24%]</span> de dégâts avec chaque paire de coups.</span>",
          "<span class='text-gray-500'>Si Frénésie touche un ennemi, sa Vitesse d'Attaque est augmentée de +20% pendant 3 secondes, jusqu'à +60%.</span>",
        ],
        footer: "Dégâts Physiques <br/> Nécessite des armes doubles",
      },
    ],
  },
  {
    image: "/skill-tech/category_core.png",
    id: 2,
    next_id: 3,
    label: "Principal",
    top: "19.7813%",
    left: "24.2791%",
    options: [
      {
        id: 1,
        image: "/skill-tech/chain_lightning.png",
        label: "Chaîne d'Éclairs",
        details: [
          "Coût en Mana : 15",
          "Coup de Chance : 50% ",
          "<span class='text-gray-500'>Lancez un éclair qui rebondit entre les ennemis proches, infligeant <span class='text-yellow-500'>[33%]</span> de dégâts.</span>",
        ],
        footer: "Dégâts de Foudre",
      },
      {
        id: 2,
        image: "/skill-tech/charged_bolts.png",
        label: "Éclairs Chargés",
        details: [
          "Coût en Mana : 15",
          "Coup de Chance : 50% ",
          "<span class='text-gray-500'>Tirez des éclairs chargés qui se déplacent aléatoirement, infligeant <span class='text-yellow-500'>[5%]</span> de dégâts chacun.</span>",
        ],
        footer: "Dégâts de Foudre",
      },
      {
        id: 3,
        image: "/skill-tech/fireball.png",
        label: "Boule de Feu",
        details: [
          "Coût en Mana : 20",
          "Coup de Chance : 30% ",
          "<span class='text-gray-500'>Lancez une boule de feu qui explose à l'impact, infligeant <span class='text-yellow-500'>[24%]</span> de dégâts dans la zone.</span>",
        ],
        footer: "Dégâts de Feu",
      },
      {
        id: 4,
        image: "/skill-tech/frozen_orb.png",
        label: "Orbe Gelé",
        details: [
          "Coût en Mana : 25",
          "Coup de Chance : 40% ",
          "<span class='text-gray-500'>Créez un orbe de glace qui explose en éclats glacés, infligeant <span class='text-yellow-500'>[30%]</span> de dégâts.</span>",
        ],
        footer: "Dégâts de Glace",
      },
      {
        id: 5,
        image: "/skill-tech/ice_shards.png",
        label: "Éclats de Glace",
        details: [
          "Coût en Mana : 15",
          "Coup de Chance : 33% ",
          "<span class='text-gray-500'>Lancez des éclats de glace acérés, infligeant <span class='text-yellow-500'>[18%]</span> de dégâts et ralentissant les ennemis.</span>",
        ],
        footer: "Dégâts de Glace",
      },
      {
        id: 6,
        image: "/skill-tech/incinerate.png",
        label: "Incinérer",
        details: [
          "Coût en Mana : 10 par seconde",
          "Coup de Chance : 20% ",
          "<span class='text-gray-500'>Canalisez un jet de flammes, infligeant <span class='text-yellow-500'>[40%]</span> de dégâts par seconde aux ennemis touchés.</span>",
        ],
        footer: "Dégâts de Feu",
      },
    ],
  },
  {
    image: "/skill-tech/category_defensive.png",
    id: 3,
    next_id: null,
    label: "Défensif",
    top: "35.2723%",
    left: "57.3472%",
    options: [
      {
        id: 1,
        image: "/skill-tech/bash.png",
        label: "Coup",
        details: [
          "Génération de Furie : 15",
          "Coup de Chance : 50% ",
          "<span class='text-gray-500'>Frappez l'ennemi avec votre arme, infligeant <span class='text-yellow-500'>[33%]</span> de dégâts. Après avoir frappé les ennemis 4 fois, votre prochain Coup les étourdira pendant 1,25 secondes, passant à 2 secondes si vous utilisez une arme à deux mains.</span>",
        ],
        footer: "Dégâts Physiques",
      },
      {
        id: 2,
        image: "/skill-tech/flay.png",
        label: "Écorcher",
        details: [
          "Génération de Furie : 15",
          "Coup de Chance : 50% ",
          "<span class='text-gray-500'>Écorchez l'ennemi, infligeant <span class='text-yellow-500'>[5%]</span> de dégâts et infligeant <span class='text-yellow-500'>[44%]</span> de dégâts de Saignement sur 5 secondes.</span>",
        ],
        footer: "Dégâts Physiques <br/> Nécessite une arme tranchante",
      },
      {
        id: 3,
        image: "/skill-tech/frenzy.png",
        label: "Frénésie",
        details: [
          "Génération de Furie : 4",
          "Coup de Chance : 30% ",
          "<span class='text-gray-500'>Déchaînez une rafale rapide de coups, infligeant <span class='text-yellow-500'>[24%]</span> de dégâts avec chaque paire de coups.</span>",
          "<span class='text-gray-500'>Si Frénésie touche un ennemi, sa Vitesse d'Attaque est augmentée de +20% pendant 3 secondes, jusqu'à +60%.</span>",
        ],
        footer: "Dégâts Physiques <br/> Nécessite des armes doubles",
      },
    ],
  },
];

export const levelRanges = [
  { min: 0, max: 2, index: 0 },
  { min: 2, max: 6, index: 1 },
  { min: 6, max: 11, index: 2 },
  { min: 11, max: 16, index: 3 },
  { min: 16, max: 23, index: 4 },
  { min: 23, max: 33, index: 5 },
];

export const bossPowers = [
  { id: 1, label: "Les serres de Allek", image: "/gears/charge.png" },
  { id: 2, label: "Skull enflammé d'Andariel", image: "/gears/charge.png" },
  { id: 3, label: "Ashavas Poison Breath", image: "/gears/charge.png" },
  { id: 4, label: "Minerai explosif de l'avarice", image: "/gears/charge.png" },
  {
    id: 5,
    label: "Bête dans le grésil de la glace",
    image: "/gears/charge.png",
  },
  { id: 6, label: "Traing de Beastmaster", image: "/gears/charge.png" },
  {
    id: 7,
    label: "Le leurre de cristal de Belial",
    image: "/gears/charge.png",
  },
  {
    id: 8,
    label: "Les faisceaux oculaires de Belial",
    image: "/gears/charge.png",
  },
  { id: 9, label: "Sabotage du chantage", image: "/gears/charge.png" },
  { id: 10, label: "Duriel's Bendow", image: "/gears/charge.png" },
  {
    id: 11,
    label: "La perturbation de Fair Reaper",
    image: "/gears/charge.png",
  },
  { id: 12, label: "Square de Grigoire", image: "/gears/charge.png" },
  {
    id: 13,
    label: "Harbinger de la volée de Haterd",
    image: "/gears/charge.png",
  },
  {
    id: 14,
    label: "La hâte de l'étreinte de Haterd",
    image: "/gears/charge.png",
  },
  { id: 15, label: "Les étincelles de Kirma", image: "/gears/charge.png" },
  {
    id: 16,
    label: "Le vent de la haine de Lilith",
    image: "/gears/charge.png",
  },
  { id: 17, label: "Pool de sang de Lord Zir", image: "/gears/charge.png" },
  {
    id: 18,
    label: "Oeil de tireur d'élite hors-la-loi",
    image: "/gears/charge.png",
  },
  { id: 19, label: "Les flammes de Sinerat", image: "/gears/charge.png" },
  { id: 20, label: "Toxines de Slerg", image: "/gears/charge.png" },
  { id: 21, label: "Rage de Torusk", image: "/gears/charge.png" },
  { id: 22, label: "Bombes lobées d'Urivar", image: "/gears/charge.png" },
  { id: 23, label: "La vie de Varshan vole", image: "/gears/charge.png" },
  {
    id: 24,
    label: "Poutre thoracique de Deat errant",
    image: "/gears/charge.png",
  },
];

export const bossPowers9 = [
  { id: 1, label: "Bottled Wind", image: "/gears/bot.png" },
  { id: 2, label: "Invigorating Helix", image: "/gears/invi.png" },
  { id: 3, label: "Jagged Bramble", image: "/gears/jag.png" },
  { id: 4, label: "Luminous Gem", image: "/gears/lumi.png" },
  { id: 5, label: "Murky Essence", image: "/gears/mur.png" },
  { id: 6, label: "Reactive Ooze", image: "/gears/rea.png" },
  { id: 7, label: "Shifting Powder", image: "/gears/shif.png" },
  { id: 8, label: "Tendrilous Bundle", image: "/gears/tend.png" },
  { id: 9, label: "Thunderous Particle", image: "/gears/tra.png" },
  { id: 10, label: "Volatile Spark", image: "/gears/vola.png" },
  { id: 11, label: "Potent Alloy", image: "/gears/fras.png" },
  { id: 12, label: "Sapping Crux", image: "/gears/pot.png" },
  { id: 13, label: "Sharpening Gizmo", image: "/gears/sap.png" },
  { id: 14, label: "Bloody Charm", image: "/gears/sha.png" },
  { id: 15, label: "Floaty Bobble", image: "/gears/blo.png" },
  { id: 16, label: "Frigid Heart", image: "/gears/floa.png" },
  { id: 17, label: "Nightmare Orb", image: "/gears/fri.png" },
  { id: 18, label: "Pressurized Steam", image: "/gears/nig.png" },
];

export const bossPowers9main = [
  { id: 1, label: "Corrosive Vapor", image: "/gears/vapor.png" },
  { id: 2, label: "Glacial Nimbus", image: "/gears/nimbus.png" },
  { id: 3, label: "Nebulous Extract", image: "/gears/extract.png" },
  { id: 4, label: "Smoldering Ember", image: "/gears/ember.png" },
  { id: 5, label: "Thunderous Particle", image: "/gears/particle5.png" },
];

export const catalystPowers = [
  {
    id: 1,
    label: "Astral Pillar",
    image: "/gears/astr.png",
    description: "Increases Strength by 10%",
  },
  {
    id: 2,
    label: "Celestial Surge",
    image: "/gears/celes.png",
    description: "Increases Agility by 10%",
  },
  {
    id: 3,
    label: "Cosmic Anomaly",
    image: "/gears/cos.png",
    description: "Increases Intelligence by 10%",
  },
  {
    id: 4,
    label: "Disintegrate",
    image: "/gears/dis.png",
    description: "Increases Intelligence by 10%",
  },
  {
    id: 5,
    label: "Propulsion",
    image: "/gears/pro.png",
    description: "Increases Intelligence by 10%",
  },
];
