 {
    id: 1,
    label: "Tableau de départ",
    top: 0,
    left: 0,
    image: "/paragon/barbarian/necromancer.png",
    str: 70,
    dex: 39,
    int: 10,
    will: 39,
    item_top: null,
    is_active: true,
    bord: [
      [
        {
          id: "barbarian_1_1",
          active: false,
          index: 10,
          direction: "top",
          link: true,
          image: "/paragon/barbarian/Gate_active.png",
          label: "Porte de fixation de la carte",
          options: ["5 Force", "5 Intelligence", "5 Volonté", "5 Dextérité"],
          activable_ids: ["barbarian_1_3"],
        },
      ],
      [
        {
          id: "barbarian_1_2",
          activable_ids: ["barbarian_1_5", "barbarian_1_3"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "barbarian_1_3",
          activable_ids: ["barbarian_1_1", "barbarian_1_2", "barbarian_1_4"],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
        {
          id: "barbarian_1_4",
          activable_ids: ["barbarian_1_6", "barbarian_1_3"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
      ],
      [
        {
          id: "barbarian_1_5",
          activable_ids: ["barbarian_1_2", "barbarian_1_7"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "barbarian_1_6",
          activable_ids: ["barbarian_1_4", "barbarian_1_8"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
      ],
      [
        {
          id: "barbarian_1_7",
          activable_ids: ["barbarian_1_5", "barbarian_1_10", "barbarian_1_60"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud magique",
          options: ["50% dégâts physiques"],
          bg: "magic",
        },
        {
          id: "barbarian_1_8",
          activable_ids: ["barbarian_1_6", "barbarian_1_11", "barbarian_1_61"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud magique",
          options: ["5 Armure"],
          bg: "magic",
        },
        {
          id: "barbarian_1_60",
          activable_ids: ["barbarian_1_9", "barbarian_1_7"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          bg: "magic",
        },
        {
          id: "barbarian_1_61",
          activable_ids: ["barbarian_1_12", "barbarian_1_8"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
          bg: "magic",
        },
      ],
      [
        {
          id: "barbarian_1_9",
          activable_ids: [
            "barbarian_1_60",
            "barbarian_1_14",
            "barbarian_1_62",
            "barbarian_1_10",
          ],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          bg: "magic",
        },
        {
          id: "barbarian_1_10",
          activable_ids: ["barbarian_1_7", "barbarian_1_15", "barbarian_1_9"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud rare",
          secondLabel: "La force brute",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          options: [
            "10 % de dégâts physiques",
            "10 Force",
            "Bonus : 10 % de dégâts physiques supplémentaires si les conditions requises sont remplies :",
            "175/160 Dextérité",
          ],
          bg: "rare",
        },
        {
          id: "barbarian_1_11",
          activable_ids: ["barbarian_1_8", "barbarian_1_16", "barbarian_1_12"],
          active: false,
          index: 11,
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud rare",
          secondLabel: "Force de Fer",
          options: [
            "100 Armure",
            "10 Force",
            "Bonus : 100 points d'armure supplémentaires si les conditions sont remplies :",
            "174/160 Volonté",
          ],
          bg: "rare",
        },
        {
          id: "barbarian_1_12",
          activable_ids: [
            "barbarian_1_61",
            "barbarian_1_17",
            "barbarian_1_11",
            "barbarian_1_62",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
          bg: "magic",
        },
        {
          id: "barbarian_1_62",
          activable_ids: ["barbarian_1_13", "barbarian_1_9"],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          options: [
            "100 Armure",
            "10 Force",
            "Bonus : 100 points d'armure supplémentaires si les conditions sont remplies :",
            "174/160 Volonté",
          ],
        },
        {
          id: "barbarian_1_62",
          activable_ids: ["barbarian_1_18", "barbarian_1_12"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/int_active.png",
          label: "Nœud magique",
          options: ["7 Volonté"],
        },
      ],
      [
        {
          id: "barbarian_1_13",
          activable_ids: [
            "barbarian_1_62",
            "barbarian_1_20",
            "barbarian_1_63",
            "barbarian_1_14",
          ],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_14",
          activable_ids: [
            "barbarian_1_9",
            "barbarian_1_21",
            "barbarian_1_13",
            "barbarian_1_15",
          ],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud magique",
          options: ["7 Dextérité"],
          bg: "magic",
        },
        {
          id: "barbarian_1_15",
          activable_ids: ["barbarian_1_10", "barbarian_1_22", "barbarian_1_14"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud magique",
          secondLabel: "La force brute",
          options: ["5 % de dégâts physiques"],
          bg: "magic",
        },
        {
          id: "barbarian_1_16",
          activable_ids: ["barbarian_1_11", "barbarian_1_24", "barbarian_1_17"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud magique",
          options: ["50 Armure"],
          bg: "magic",
        },
        {
          id: "barbarian_1_17",
          activable_ids: [
            "barbarian_1_12",
            "barbarian_1_25",
            "barbarian_1_16",
            "barbarian_1_18",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud magique",
          options: ["7 Volonté"],
          bg: "magic",
        },
        {
          id: "barbarian_1_18",
          activable_ids: [
            "barbarian_1_62",
            "barbarian_1_26",
            "barbarian_1_17",
            "barbarian_1_64",
          ],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "barbarian_1_63",
          activable_ids: ["barbarian_1_19", "barbarian_1_13"],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
        {
          id: "barbarian_1_64",
          activable_ids: ["barbarian_1_27", "barbarian_1_18"],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
      ],
      [
        {
          id: "barbarian_1_19",
          activable_ids: [
            "barbarian_1_63",
            "barbarian_1_67",
            "barbarian_1_65",
            "barbarian_1_20",
          ],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_20",
          activable_ids: [
            "barbarian_1_13",
            "barbarian_1_28",
            "barbarian_1_19",
            "barbarian_1_21",
          ],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_21",
          activable_ids: [
            "barbarian_1_14",
            "barbarian_1_29",
            "barbarian_1_20",
            "barbarian_1_22",
          ],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
        {
          id: "barbarian_1_22",
          activable_ids: [
            "barbarian_1_15",
            "barbarian_1_30",
            "barbarian_1_21",
            "barbarian_1_23",
          ],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "barbarian_1_23",
          active: null,
          index: 10,
          link: true,
          image: "/paragon/barbarian/tile_bg_glyph.png",
          label: "Glyph_id: 1,e de socket",
          label: "Glyph_id: 4,e de socket",
          is_icon: true,
          activable_ids: ["barbarian_1_31", "barbarian_1_22", "barbarian_1_24"],
        },
        {
          id: "barbarian_1_24",
          activable_ids: [
            "barbarian_1_16",
            "barbarian_1_32",
            "barbarian_1_23",
            "barbarian_1_25",
          ],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "barbarian_1_25",
          activable_ids: [
            "barbarian_1_17",
            "barbarian_1_33",
            "barbarian_1_24",
            "barbarian_1_26",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "barbarian_1_26",
          activable_ids: [
            "barbarian_1_18",
            "barbarian_1_34",
            "barbarian_1_25",
            "barbarian_1_27",
          ],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_27",
          activable_ids: [
            "barbarian_1_64",
            "barbarian_1_68",
            "barbarian_1_26",
            "barbarian_1_66",
          ],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
        {
          id: "barbarian_1_65",
          activable_ids: ["barbarian_1_19"],
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_66",
          activable_ids: ["barbarian_1_27"],
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
      ],
      [
        {
          id: "barbarian_1_28",
          activable_ids: [
            "barbarian_1_20",
            "barbarian_1_69",
            "barbarian_1_67",
            "barbarian_1_29",
          ],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_29",
          activable_ids: [
            "barbarian_1_21",
            "barbarian_1_35",
            "barbarian_1_28",
            "barbarian_1_30",
          ],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "barbarian_1_30",
          activable_ids: [
            "barbarian_1_22",
            "barbarian_1_36",
            "barbarian_1_29",
            "barbarian_1_31",
          ],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_31",
          activable_ids: [
            "barbarian_1_23",
            "barbarian_1_37",
            "barbarian_1_30",
            "barbarian_1_32",
          ],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_32",
          activable_ids: [
            "barbarian_1_24",
            "barbarian_1_38",
            "barbarian_1_31",
            "barbarian_1_33",
          ],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "barbarian_1_33",
          activable_ids: [
            "barbarian_1_25",
            "barbarian_1_39",
            "barbarian_1_32",
            "barbarian_1_34",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_34",
          activable_ids: [
            "barbarian_1_26",
            "barbarian_1_70",
            "barbarian_1_33",
            "barbarian_1_68",
          ],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
        {
          id: "barbarian_1_67",
          activable_ids: ["barbarian_1_19", "barbarian_1_28"],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
        {
          id: "barbarian_1_68",
          activable_ids: ["barbarian_1_27", "barbarian_1_34"],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
      ],
      [
        {
          id: "barbarian_1_35",
          activable_ids: [
            "barbarian_1_29",
            "barbarian_1_71",
            "barbarian_1_69",
            "barbarian_1_36",
          ],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "barbarian_1_36",
          activable_ids: [
            "barbarian_1_30",
            "barbarian_1_40",
            "barbarian_1_35",
            "barbarian_1_37",
          ],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_37",
          activable_ids: ["barbarian_1_31", "barbarian_1_36", "barbarian_1_38"],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "barbarian_1_38",
          activable_ids: [
            "barbarian_1_32",
            "barbarian_1_41",
            "barbarian_1_37",
            "barbarian_1_39",
          ],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
        {
          id: "barbarian_1_39",
          activable_ids: [
            "barbarian_1_33",
            "barbarian_1_72",
            "barbarian_1_38",
            "barbarian_1_70",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "barbarian_1_69",
          activable_ids: ["barbarian_1_28", "barbarian_1_35"],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_70",
          activable_ids: ["barbarian_1_34", "barbarian_1_39"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/int_active.png",
          label: "Nœud normal",
          options: ["5 Force"],
        },
      ],
      [
        {
          id: "barbarian_1_40",
          activable_ids: ["barbarian_1_36", "barbarian_1_43", "barbarian_1_71"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          glyph_ids: [3,7,8,11,16,19,21],
        },
        {
          id: "barbarian_1_41",
          activable_ids: ["barbarian_1_38", "barbarian_1_44", "barbarian_1_72"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_71",
          activable_ids: ["barbarian_1_35", "barbarian_1_42", "barbarian_1_40"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_72",
          activable_ids: ["barbarian_1_39", "barbarian_1_45", "barbarian_1_41"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
      ],
      [
        {
          id: "barbarian_1_42",
          activable_ids: ["barbarian_1_71", "barbarian_1_46", "barbarian_1_43"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          label: "Nœud magique",
          options: ["2% de vie maximale"],
          bg: "magic",
        },
        {
          id: "barbarian_1_43",
          activable_ids: ["barbarian_1_40", "barbarian_1_47", "barbarian_1_42"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/str_active.png",
          label: "Nœud normal",
          glyph_ids: [1, 4, 5, 6,9,12,13,14,17,18,20], // Multiple glyph IDs
          _id: 1,
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_44",
          activable_ids: ["barbarian_1_41", "barbarian_1_48", "barbarian_1_45"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/dex_active.png",
          glyph_ids: [2,10,15,22,23],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          options: ["5 % de dégâts physiques"],
        },
        {
          id: "barbarian_1_45",
          activable_ids: ["barbarian_1_72", "barbarian_1_52", "barbarian_1_44"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          label: "Nœud magique",
          options: ["2% de vie maximale"],
          bg: "magic",
        },
      ],
      [
        {
          id: "barbarian_1_46",
          activable_ids: [
            "barbarian_1_42",
            "barbarian_1_49",
            "barbarian_1_73",
            "barbarian_1_47",
          ],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          label: "Nœud rare",
          secondLabel: "Ténacité",
          options: [
            "4% de vie maximale",
            " 100 Armure",
            "Bonus :4 % de vie maximale supplémentaires si les conditions requises sont remplies :",
            "177/200 Force",
            "174/160 Volonté",
          ],
          bg: "rare",
        },
        {
          id: "barbarian_1_47",
          activable_ids: ["barbarian_1_43", "barbarian_1_46"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          label: "Nœud magique",
          options: ["2% de vie maximale"],
          bg: "magic",
        },
        {
          id: "barbarian_1_48",
          activable_ids: ["barbarian_1_44", "barbarian_1_52"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          label: "Nœud magique",
          options: ["2% de vie maximale"],
          bg: "magic",
        },
        {
          id: "barbarian_1_52",
          activable_ids: [
            "barbarian_1_45",
            "barbarian_1_50",
            "barbarian_1_48",
            "barbarian_1_74",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud rare",
          secondLabel: "La force brute",
          options: [
            "10 % de dégâts physiques",
            "10 Force",
            "Bonus : 10 % de dégâts physiques supplémentaires si les conditions requises sont remplies :",
            "177/200 Dextérité",
          ],
          bg: "rare",
        },
        {
          id: "barbarian_1_73",
          activable_ids: ["barbarian_1_46"],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Nœud magique",
          options: ["2% de vie maximale"],
          bg: "magic",
        },
        {
          id: "barbarian_1_74",
          activable_ids: ["barbarian_1_52"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud rare",
          secondLabel: "La force brute",
          options: [
            "10 % de dégâts physiques",
            "10 Force",
            "Bonus : 10 % de dégâts physiques supplémentaires si les conditions requises sont remplies :",
            "177/200 Dextérité",
          ],
          bg: "magic",
        },
      ],
      [
        {
          id: "barbarian_1_49",
          activable_ids: ["barbarian_1_46", "barbarian_1_51"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Nœud rare",
          options: ["50 Armure"],
          bg: "magic",
        },
        {
          id: "barbarian_1_50",
          activable_ids: ["barbarian_1_52", "barbarian_1_56"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          label: "Nœud rare",
          secondLabel: "La force brute",
          options: ["5 % de dégâts physiques"],
          bg: "magic",
        },
      ],
      [
        {
          id: "barbarian_1_51",
          activable_ids: ["barbarian_1_53"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "barbarian_1_53",
          activable_ids: ["barbarian_1_54", "barbarian_1_57"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "barbarian_1_54",
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
          opened: true,
        },
        {
          id: "barbarian_1_55",
          activable_ids: ["barbarian_1_54", "barbarian_1_59"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
        {
          id: "barbarian_1_56",
          activable_ids: ["barbarian_1_55"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
      ],
      [
        {
          id: "barbarian_1_57",
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
          opened: true,
        },
        {
          id: "barbarian_1_58",
          active: null,
          index: 10,
          link: false,
          image: "/paragon/barbarian/barbarian.png",
          label: "Glyph_id: 1,e de socket",
          label: "Glyph_id: 4,e de socket",
          is_icon: true,
        },
        {
          id: "barbarian_1_59",
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
          opened: true,
        },
      ],
    ],
  },