{}
{
  image: "/paragon/barbarian/DamageToCC_active.png",
  label: "Nœud magique",
  options: ["+17.5% de dégâts contre les cibles subissant une perte de contrôle"],

  image: "/paragon/barbarian/Spirit_active.png",
  label: "Nœud magique",
  options: ["+1 de ressource par victime pour Esprit"],

  image: "/paragon/barbarian/Fury_active.png",
  label: "Nœud magique",
  options: ["+2[Fureur maximum]"],

  image: "/paragon/barbarian/Dodge_active.png",
  label: "Nœud magique",
  options: ["1.0% de chances d'esquiver"],

  image: "/paragon/barbarian/DamageBleed_active.png",
  label: "Nœud magique",
  options: ["+15.0% de dégâts physiques sur la durée"],

  image: "/paragon/barbarian/EarthquakeDamage_active.png",
  label: "Nœud magique",
  options: ["+22.5% de dégâts pour Tremblement de terre"],

  image: "/paragon/barbarian/DustDevilArea_active.png",
  label: "Nœud magique",
  options: [
    "+5.0% de taille pour Tourbillon de poussière"
  ],

  image: "/paragon/barbarian/CriticalDamageEarth_active.png",
  label: "Nœud magique",
  options: [
    "+5.0% à la durée pour Tremblement de terre"
  ],
  label: "Nœud magique",
  options: [
    "+5.0% à la durée pour Tremblement de terre"
  ],

  image: "/paragon/barbarian/DustDevilSize_active.png",
  label: "Nœud magique",
  options: [
    "+10.0% de dégâts pour Tourbillon de poussière"
  ],

  image: "/paragon/barbarian/Damage_active.png",
  label: "Nœud magique",
  options: ["+10.0% de dégâts physiques"],

  image: "/paragon/barbarian/DamageToVulnerable_active.png",
  label: "Nœud magique",
  options: ["+12.5% de dégâts contre les cibles vulnérables"],

  image: "/paragon/barbarian/CriticalDamage_active.png",
  label: "Nœud magique",
  options: ["+15.0% de dégâts critiques"],

  image: "/paragon/barbarian/DamageWhileHealthy_active.png",
  label: "Noeud magique",
  options: ["+12.5% de dégâts"],

  image: "/paragon/barbarian/DamageReductionWhileFortified_active.png",
  label: "Noeud magique",
  options: ["+3.3% de résistance maximum aux dégâts de feu"],

  image: "/paragon/barbarian/ResistanceAll_active.png",
  label: "Noeud magique",
  options: ["+1.5% de résistance maximum aux dégâts de feu"],
  label: "Noeud magique",
  options: ["+1.5% de résistance maximum aux dégâts de feu"],

  image: "/paragon/barbarian/DamageToBleed_active.png",
  label: "Noeud magique",
  options: ["+10.0% de dégâts contre les cibles sous l'effet : Saignement"],
  
  image: "/paragon/barbarian/DamageToNear_active.png",
  label: "Noeud magique",
  options: ["+12.0% de dégâts"],
  
  image: "/paragon/barbarian/Dex_active.png",
  label: "Noeud magique",
  options: ["7 Dextérité"],

  image: "/paragon/barbarian/Will_active.png",
  label: "Noeud magique",
  options: ["+7 volonte"],

  image: "/paragon/barbarian/HPPercent_active.png",
  label: "Noeud magique",
  options: ["Maximum de vie augmenté de 2.0%"],

  image: "/paragon/barbarian/Armor_active.png",
  label: "Noeud magique",
  options: ["+1.5 à l'armure"],
  
  image: "/paragon/barbarian/HealingBonus_active.png",
  label: "Nœud magique",
  options: ["+3% de soins reçus"],

  image: "/paragon/barbarian/BerserkDamage_active.png",
  label: "Nœud magique",
  options: ["+10.0% de dégâts pendant Rage du berserker"],

  image: "/paragon/barbarian/Damage_active.png",
  label: "Nœud rare",
  secondLabel: "Puissance brute",
  options: [
    "+24.0% de dégâts",
    "+10 force",
    "Bonus : ajoute +20.0% de dégâts si ces conditions sont remplies :",
    "174/210 dextérité",
  ],
}

{}
{


// last power (Spiritborn)
// glyph_ids: [1,3,5,11,12,13,16,21],str
// glyph_ids: [2,4,9,17,18],int
// glyph_ids: [6,7,,8,10,14,15,19,20,22],dex


// 2nd last power (Sorcerer)
// glyph_ids: [12,13,15,14,20,22],will
// glyph_ids: [1,2,3,7,8,9,17,21],int
// glyph_ids: [4,5,,6,10,11,14,18,19,23],dex

// 3 Necromancer Paragon
// glyph_ids: [8,9,14,15,16,18,22,],will
// glyph_ids: [2,3,4,5,6,7,10,12,17,20,19],int
// glyph_ids: [1,11,13,23,21],dex

// 4 (voleur/rogue)3aragon
glyph_ids: [1,2,9,11,18,22],str
glyph_ids: [3,6,7,10,16,17,20,21],int
glyph_ids: [4,5,8,12,13,14,15,19,23],dex
}



{
          image: "/paragon/barbarian/Int_ac.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],

          image: "/paragon/barbarian/Str_ac.png",
          label: "Nœud normal",
          options: ["+5 Force"],

          image: "/paragon/barbarian/Will_ac.png",
          label: "Nœud normal",
          options: ["+5 volonte"],

          image: "/paragon/barbarian/Dex_ac.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
},



{}
[
        {
          id: "druid_2_38",
          active: null,
          index: 5,
          link: true,
          image: "/paragon/tile_bg_glyph.png",
          is_icon: true,
        },

        {
          id: "rogue_10_173",
          active: null,
          index: 12,
          link: true,
          image: "/paragon/tile_bg_glyph.png",
          is_icon: true,
        },
  ]



  {}
  {
    id: 4,
    label: "Dévastation terrestre",
    top: 0,
    left: 0,
    image: "/paragon/barbarian/necromancer.png",
    str: 70,
    dex: 39,
    int: 10,
    will: 39,
    item_top: null,
    is_active: false,
    bord: [
      [
        {
          id: "druid_4_1",
          active: false,
          index: 10,
          direction: "top",
          link: true,
          image: "/paragon/barbarian/Gate_active.png",
          label: "Porte de fixation de la carte",
          options: ["5 Force", "5 Intelligence", "5 Volonté", "5 Dextérité"],
        },
      ],
      [
        {
          id: "druid_4_3",
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
          opened: true,
        },
        {
          id: "druid_4_4",
          activable_ids: ["druid_4_161", "druid_4_3"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
      ],
      [
        {
          id: "druid_4_160",
          activable_ids: ["druid_4_7", "druid_4_5"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_5",
          activable_ids: ["druid_4_160", "druid_4_159"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
        {
          id: "druid_4_159",
          activable_ids: ["druid_4_3", "druid_4_8", "druid_4_5", "druid_4_161"],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_161",
          activable_ids: [
            "druid_4_4",
            "druid_4_60",
            "druid_4_159",
            "druid_4_187",
          ],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_187",
          activable_ids: ["druid_4_61", "druid_4_161"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_6",
          activable_ids: ["druid_4_63"],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/CriticalDamage_active.png",
          label: "Nœud magique",
  options: ["+15.0% de dégâts critiques"],
          bg: "magic",
        },
      ],
      [
        {
          id: "druid_4_7",
          activable_ids: ["druid_4_160", "druid_4_9"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_8",
          activable_ids: ["druid_4_159", "druid_4_60"],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_60",
          activable_ids: ["druid_4_161", "druid_4_8", "druid_4_61"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
        {
          id: "druid_4_61",
          activable_ids: [
            "druid_4_187",
            "druid_4_10",
            "druid_4_60",
            "druid_4_62",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_62",
          activable_ids: ["druid_4_11", "druid_4_61", "druid_4_63"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/DamageToCC_active.png",
          label: "Nœud magique",
options: ["+17.5% de dégâts contre les cibles subissant une perte de contrôle"],
          bg: "magic",
        },
        {
          id: "druid_4_63",
          activable_ids: [
            "druid_4_6",
            "druid_4_12",
            "druid_4_62",
            "druid_4_64",
          ],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/DamageToCC_active.png",
          label: "Nœud rare",
secondLabel: "Oppression",
options: [
  "+35.0% de dégâts contre les cibles subissant une perte de contrôle",
  "+30.0% de dégâts critiques",
  "Bonus : ajoute +35.0% de dégâts contre les cibles subissant une perte de contrôle si ces conditions sont remplies :",
  "415 intelligence"
],
          bg: "rare",
        },
        {
          id: "druid_4_64",
          activable_ids: ["druid_4_63"],
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/CriticalDamage_active.png",
          label: "Nœud magique",
  options: ["+15.0% de dégâts critiques"],
          bg: "magic",
        },
      ],
      [
        {
          id: "druid_4_9",
          activable_ids: ["druid_4_7", "druid_4_17", "druid_4_74"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_10",
          activable_ids: ["druid_4_61", "druid_4_18", "druid_4_11"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_11",
          activable_ids: [
            "druid_4_62",
            "druid_4_65",
            "druid_4_10",
            "druid_4_12",
          ],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/DamageToCC_active.png",
          label: "Nœud magique",
options: ["+17.5% de dégâts contre les cibles subissant une perte de contrôle"],

          bg: "magic",
        },
        {
          id: "druid_4_12",
          activable_ids: ["druid_4_63", "druid_4_11"],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/CriticalDamage_active.png",
          label: "Nœud magique",
  options: ["+15.0% de dégâts critiques"],
          bg: "magic",
        },
        {
          id: "druid_4_73",
          activable_ids: ["druid_4_15", "druid_4_74"],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Noeud magique",
  options: ["+1.5 à l'armure"],
          bg: "magic",
        },
        {
          id: "druid_4_74",
          activable_ids: ["druid_4_16", "druid_4_73", "druid_4_9"],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
      ],
      [
        {
          id: "druid_4_13",
          activable_ids: ["druid_4_19", "druid_4_14"],
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Noeud magique",
  options: ["+1.5 à l'armure"],
          bg: "magic",
        },
        {
          id: "druid_4_14",
          activable_ids: ["druid_4_20", "druid_4_13", "druid_4_15"],
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Nœud rare",
secondLabel: "Résilience imprégnée",
options: [
  "+5.0% de réduction des dégâts",
  "+3.0% de résistance à tous les éléments",
  "Bonus : ajoute +5.0% de réduction des dégâts si ces conditions sont remplies :",
  "415 intelligence"
],
          bg: "rare",
        },
        {
          id: "druid_4_15",
          activable_ids: ["druid_4_73", "druid_4_14", "druid_4_16"],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/ResistanceAll_active.png",
          bg: "magic",
        },
        {
          id: "druid_4_16",
          activable_ids: [
            "druid_4_74",
            "druid_4_21",
            "druid_4_15",
            "druid_4_17",
          ],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_17",
          activable_ids: ["druid_4_9", "druid_4_22", "druid_4_16"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_18",
          activable_ids: ["druid_4_10", "druid_4_26", "druid_4_65"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_65",
          activable_ids: ["druid_4_11", "druid_4_27", "druid_4_18"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
      ],
      [
        {
          id: "druid_4_19",
          activable_ids: ["druid_4_13", "druid_4_28", "druid_4_20"],
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Noeud magique",
  options: ["+1.5 à l'armure"],
          bg: "magic",
        },
        {
          id: "druid_4_20",
          activable_ids: ["druid_4_14", "druid_4_29", "druid_4_19"],
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/ResistanceAll_active.png",
          bg: "magic",
        },
        {
          id: "druid_4_21",
          activable_ids: ["druid_4_16", "druid_4_22"],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_22",
          activable_ids: [
            "druid_4_17",
            "druid_4_31",
            "druid_4_21",
            "druid_4_23",
          ],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_23",
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
          activable_ids: ["druid_4_22", "druid_4_24"],
        },
        {
          id: "druid_4_24",
          activable_ids: ["druid_4_23", "druid_4_25"],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_25",
          activable_ids: ["druid_4_24", "druid_4_26"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_26",
          activable_ids: [
            "druid_4_18",
            "druid_4_32",
            "druid_4_25",
            "druid_4_27",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_27",
          activable_ids: ["druid_4_65", "druid_4_26"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
      ],
      [
        {
          id: "druid_4_28",
          activable_ids: ["druid_4_19", "druid_4_37", "druid_4_29"],
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_29",
          activable_ids: [
            "druid_4_20",
            "druid_4_38",
            "druid_4_28",
            "druid_4_30",
          ],
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_30",
          activable_ids: ["druid_4_39", "druid_4_29"],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_31",
          activable_ids: ["druid_4_22", "druid_4_68"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_32",
          activable_ids: ["druid_4_26", "druid_4_71"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
      ],

      [
        {
          id: "druid_4_35",
          activable_ids: ["druid_4_40", "druid_4_36"],
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_36",
          activable_ids: ["druid_4_35", "druid_4_37"],
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_37",
          activable_ids: ["druid_4_28", "druid_4_36", "druid_4_38"],
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_38",
          activable_ids: ["druid_4_29", "druid_4_37", "druid_4_39"],
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_39",
          activable_ids: [
            "druid_4_30",
            "druid_4_41",
            "druid_4_38",
            "druid_4_67",
          ],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_67",
          activable_ids: ["druid_4_39", "druid_4_68"],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_68",
          activable_ids: [
            "druid_4_31",
            "druid_4_162",
            "druid_4_67",
            "druid_4_69",
          ],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_69",
          activable_ids: ["druid_4_163", "druid_4_68"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_70",
          activable_ids: ["druid_4_75", "druid_4_71"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5, 7, 12, 13, 15, 16, 17, 18, 19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          bg: "magic",
        },
        {
          id: "druid_4_71",
          activable_ids: [
            "druid_4_32",
            "druid_4_76",
            "druid_4_70",
            "druid_4_72",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/DamageToCC_active.png",
          label: "Nœud magique",
options: ["+17.5% de dégâts contre les cibles subissant une perte de contrôle"],
          bg: "magic",
        },
        {
          id: "druid_4_72",
          activable_ids: ["druid_4_77", "druid_4_71"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
      ],
      [
        {
          id: "druid_4_40",
          activable_ids: ["druid_4_35", "druid_4_43"],
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_41",
          activable_ids: ["druid_4_39", "druid_4_45"],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_162",
          activable_ids: ["druid_4_68", "druid_4_163"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_163",
          activable_ids: ["druid_4_69", "druid_4_162"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Druid_active.png",
          bg: "rare",
        },
        {
          id: "druid_4_75",
          activable_ids: ["druid_4_70", "druid_4_80", "druid_4_76"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/DamageToCC_active.png",
          label: "Nœud magique",
options: ["+17.5% de dégâts contre les cibles subissant une perte de contrôle"],
          bg: "magic",
        },
        {
          id: "druid_4_76",
          activable_ids: [
            "druid_4_71",
            "druid_4_81",
            "druid_4_75",
            "druid_4_77",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          bg: "rare",
        },
        {
          id: "druid_4_77",
          activable_ids: [
            "druid_4_72",
            "druid_4_82",
            "druid_4_76",
            "druid_4_78",
          ],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5, 7, 12, 13, 15, 16, 17, 18, 19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          bg: "magic",
        },
        {
          id: "druid_4_78",
          activable_ids: ["druid_4_83", "druid_4_77"],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
      ],
      [
        {
          id: "druid_4_203",
          active: false,
          index: 0,
          direction: "left",
          link: true,
          image: "/paragon/barbarian/Gate_active.png",
          label: "Porte de fixation de la carte",
          options: ["5 Force", "5 Intelligence", "5 Volonté", "5 Dextérité"],
        },
        {
          id: "druid_4_42",
          active: false,
          index: 1,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
          bg: "magic",
          opened: true,
        },
        {
          id: "druid_4_43",
          activable_ids: [
            "druid_4_40",
            "druid_4_47",
            "druid_4_42",
            "druid_4_44",
          ],
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_44",
          activable_ids: ["druid_4_48", "druid_4_43"],
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_45",
          activable_ids: ["druid_4_41", "druid_4_52"],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_79",
          activable_ids: ["druid_4_90", "druid_4_80"],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_80",
          activable_ids: [
            "druid_4_75",
            "druid_4_91",
            "druid_4_79",
            "druid_4_81",
          ],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5, 7, 12, 13, 15, 16, 17, 18, 19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_81",
          activable_ids: [
            "druid_4_76",
            "druid_4_92",
            "druid_4_80",
            "druid_4_82",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/DamageToCC_active.png",
          label: "Nœud magique",
options: ["+17.5% de dégâts contre les cibles subissant une perte de contrôle"],
          bg: "magic",
        },
        {
          id: "druid_4_82",
          activable_ids: [
            "druid_4_77",
            "druid_4_93",
            "druid_4_81",
            "druid_4_83",
          ],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_83",
          activable_ids: ["druid_4_78", "druid_4_94", "druid_4_82"],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_84",
          activable_ids: ["druid_4_96", "druid_4_85"],
          active: false,
          index: 16,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
        {
          id: "druid_4_85",
          activable_ids: ["druid_4_97", "druid_4_84", "druid_4_86"],
          active: false,
          index: 17,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_86",
          activable_ids: ["druid_4_85", "druid_4_87"],
          active: false,
          index: 18,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_87",
          active: false,
          opened: true,
          index: 19,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_204",
          active: false,
          index: 20,
          direction: "right",
          link: true,
          image: "/paragon/barbarian/Gate_active.png",
          label: "Porte de fixation de la carte",
          options: ["5 Force", "5 Intelligence", "5 Volonté", "5 Dextérité"],
        },
      ],
      [
        {
          id: "druid_4_46",
          activable_ids: ["druid_4_42", "druid_4_47"],
          active: false,
          index: 1,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_47",
          activable_ids: [
            "druid_4_43",
            "druid_4_49",
            "druid_4_46",
            "druid_4_48",
          ],
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_48",
          activable_ids: ["druid_4_44", "druid_4_50", "druid_4_47"],
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_52",
          activable_ids: ["druid_4_45", "druid_4_167"],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_88",
          activable_ids: ["druid_4_169", "druid_4_89"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],

          bg: "magic",
        },
        {
          id: "druid_4_89",
          activable_ids: ["druid_4_170", "druid_4_88", "druid_4_90"],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/DamageEarth_active.png",

          bg: "magic",
        },
        {
          id: "druid_4_90",
          activable_ids: [
            "druid_4_79",
            "druid_4_171",
            "druid_4_89",
            "druid_4_91",
          ],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_91",
          activable_ids: [
            "druid_4_80",
            "druid_4_172",
            "druid_4_90",
            "druid_4_92",
          ],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
        {
          id: "druid_4_92",
          activable_ids: [
            "druid_4_81",
            "druid_4_173",
            "druid_4_91",
            "druid_4_93",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_93",
          activable_ids: [
            "druid_4_82",
            "druid_4_174",
            "druid_4_92",
            "druid_4_94",
          ],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_94",
          activable_ids: [
            "druid_4_83",
            "druid_4_175",
            "druid_4_93",
            "druid_4_95",
          ],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_95",
          activable_ids: ["druid_4_176", "druid_4_94", "druid_4_96"],
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_96",
          activable_ids: [
            "druid_4_84",
            "druid_4_177",
            "druid_4_95",
            "druid_4_97",
          ],
          active: false,
          index: 16,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5, 7, 12, 13, 15, 16, 17, 18, 19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_97",
          activable_ids: ["druid_4_85", "druid_4_96"],
          active: false,
          index: 17,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_98",
          activable_ids: ["druid_4_87", "druid_4_179"],
          active: false,
          index: 19,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
      ],
      [
        {
          id: "druid_4_49",
          activable_ids: ["druid_4_47", "druid_4_50"],
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_50",
          activable_ids: [
            "druid_4_48",
            "druid_4_51",
            "druid_4_49",
            "druid_4_165",
          ],
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_165",
          activable_ids: ["druid_4_53", "druid_4_50", "druid_4_166"],
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_166",
          activable_ids: ["druid_4_54", "druid_4_165", "druid_4_167"],
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_167",
          activable_ids: [
            "druid_4_52",
            "druid_4_55",
            "druid_4_166",
            "druid_4_168",
          ],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_168",
          activable_ids: ["druid_4_167", "druid_4_169"],
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_169",
          activable_ids: [
            "druid_4_88",
            "druid_4_56",
            "druid_4_168",
            "druid_4_170",
          ],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/DamageEarth_active.png",
          bg: "magic",
        },
        {
          id: "druid_4_170",
          activable_ids: [
            "druid_4_89",
            "druid_4_114",
            "druid_4_169",
            "druid_4_171",
          ],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/DamageEarth_active.png",
          bg: "rare",
        },
        {
          id: "druid_4_171",
          activable_ids: [
            "druid_4_90",
            "druid_4_115",
            "druid_4_170",
            "druid_4_172",
          ],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/DamageEarth_active.png",
          bg: "magic",
        },
        {
          id: "druid_4_172",
          activable_ids: [
            "druid_4_91",
            "druid_4_116",
            "druid_4_171",
            "druid_4_173",
          ],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5, 7, 12, 13, 15, 16, 17, 18, 19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_173",
          active: null,
          index: 12,
          link: true,
          image: "/paragon/tile_bg_glyph.png",
          bg: "magic",
          is_icon: true,
        },
        {
          id: "druid_4_174",
          activable_ids: ["druid_4_93", "druid_4_173", "druid_4_175"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
        {
          id: "druid_4_175",
          activable_ids: [
            "druid_4_94",
            "druid_4_118",
            "druid_4_174",
            "druid_4_176",
          ],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_176",
          activable_ids: [
            "druid_4_95",
            "druid_4_119",
            "druid_4_175",
            "druid_4_177",
          ],
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
          bg: "magic",
        },
        {
          id: "druid_4_177",
          activable_ids: ["druid_4_96", "druid_4_120", "druid_4_176"],
          active: false,
          index: 16,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_178",
          activable_ids: ["druid_4_122", "druid_4_179"],
          active: false,
          index: 18,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_179",
          activable_ids: ["druid_4_98", "druid_4_123", "druid_4_178"],
          active: false,
          index: 19,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
      ],
      [
        {
          id: "druid_4_51",
          activable_ids: ["druid_4_50", "druid_4_58", "druid_4_53"],
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Noeud magique",
  options: ["+1.5 à l'armure"],
          bg: "magic",
        },
        {
          id: "druid_4_53",
          activable_ids: [
            "druid_4_165",
            "druid_4_59",
            "druid_4_51",
            "druid_4_54",
          ],
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Noeud magique",
  options: ["+1.5 à l'armure"],
          bg: "magic",
        },
        {
          id: "druid_4_54",
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
          opened: true,
          activable_ids: ["druid_4_166", "druid_4_53", "druid_4_55"],
        },
        {
          id: "druid_4_55",
          activable_ids: ["druid_4_167", "druid_4_54"],
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_56",
          activable_ids: ["druid_4_169", "druid_4_114"],
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5, 7, 12, 13, 15, 16, 17, 18, 19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_114",
          activable_ids: [
            "druid_4_170",
            "druid_4_124",
            "druid_4_56",
            "druid_4_115",
          ],
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          bg: "magic",
        },
        {
          id: "druid_4_115",
          activable_ids: [
            "druid_4_171",
            "druid_4_125",
            "druid_4_114",
            "druid_4_116",
          ],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_116",
          activable_ids: [
            "druid_4_172",
            "druid_4_126",
            "druid_4_115",
            "druid_4_117",
          ],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_117",
          activable_ids: ["druid_4_173", "druid_4_127", "druid_4_116"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_118",
          activable_ids: ["druid_4_175", "druid_4_119"],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_119",
          activable_ids: [
            "druid_4_176",
            "druid_4_129",
            "druid_4_118",
            "druid_4_120",
          ],
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_120",
          activable_ids: [
            "druid_4_177",
            "druid_4_130",
            "druid_4_119",
            "druid_4_121",
          ],
          active: false,
          index: 16,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5, 7, 12, 13, 15, 16, 17, 18, 19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_121",
          activable_ids: ["druid_4_120", "druid_4_122"],
          active: false,
          index: 17,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_122",
          activable_ids: ["druid_4_178", "druid_4_121", "druid_4_123"],
          active: false,
          index: 18,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_123",
          activable_ids: ["druid_4_179", "druid_4_122"],
          active: false,
          index: 19,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
      ],
      [
        {
          id: "druid_4_57",
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          opened: true,
          activable_ids: ["druid_4_58"],
          bg: "magic",
        },
        {
          id: "druid_4_58",
          active: null,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Noeud magique",
  options: ["+1.5 à l'armure"],
          is_icon: true,
          activable_ids: ["druid_4_51", "druid_4_57", "druid_4_59"],
          bg: "rare",
        },
        {
          id: "druid_4_59",
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          opened: true,
          activable_ids: ["druid_4_53", "druid_4_58"],
          bg: "magic",
        },
        {
          id: "druid_4_124",
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
          opened: true,
          activable_ids: ["druid_4_114", "druid_4_125"],
        },
        {
          id: "druid_4_125",
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
          opened: true,
          activable_ids: ["druid_4_115", "druid_4_124", "druid_4_126"],
        },
        {
          id: "druid_4_126",
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          opened: true,
          activable_ids: [
            "druid_4_116",
            "druid_4_131",
            "druid_4_125",
            "druid_4_127",
          ],
        },
        {
          id: "druid_4_127",
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5, 7, 12, 13, 15, 16, 17, 18, 19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          opened: true,
          activable_ids: [
            "druid_4_117",
            "druid_4_184",
            "druid_4_126",
            "druid_4_128",
          ],
        },
        {
          id: "druid_4_128",
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
          opened: true,
          activable_ids: ["druid_4_132", "druid_4_127"],
        },
        {
          id: "druid_4_129",
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          opened: true,
          activable_ids: ["druid_4_119", "druid_4_134", "druid_4_130"],
        },
        {
          id: "druid_4_130",
          active: false,
          index: 16,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
          opened: true,
          activable_ids: ["druid_4_120", "druid_4_135", "druid_4_129"],
        },
      ],
      [
        {
          id: "druid_4_131",
          activable_ids: ["druid_4_126", "druid_4_138", "druid_4_184"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Armor_active.png",
          label: "Noeud magique",
  options: ["+1.5 à l'armure"],
          bg: "magic",
        },
        {
          id: "druid_4_184",
          activable_ids: [
            "druid_4_127",
            "druid_4_139",
            "druid_4_131",
            "druid_4_132",
          ],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
        {
          id: "druid_4_132",
          activable_ids: [
            "druid_4_128",
            "druid_4_140",
            "druid_4_184",
            "druid_4_133",
          ],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5, 7, 12, 13, 15, 16, 17, 18, 19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_133",
          activable_ids: ["druid_4_132", "druid_4_134"],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_134",
          activable_ids: [
            "druid_4_129",
            "druid_4_141",
            "druid_4_133",
            "druid_4_135",
          ],
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_135",
          activable_ids: [
            "druid_4_130",
            "druid_4_142",
            "druid_4_134",
            "druid_4_136",
          ],
          active: false,
          index: 16,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_136",
          activable_ids: ["druid_4_143", "druid_4_135"],
          active: false,
          index: 17,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
      ],
      [
        {
          id: "druid_4_137",
          activable_ids: ["druid_4_144", "druid_4_138"],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_138",
          activable_ids: [
            "druid_4_131",
            "druid_4_145",
            "druid_4_137",
            "druid_4_139",
          ],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1, 2, 8, 11, 14, 20, 23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_139",
          activable_ids: ["druid_4_184", "druid_4_138", "druid_4_140"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_140",
          activable_ids: ["druid_4_132", "druid_4_146", "druid_4_139"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3, 4, 6, 9, 10, 21, 22],
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_141",
          activable_ids: ["druid_4_134", "druid_4_148", "druid_4_142"],
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_142",
          activable_ids: [
            "druid_4_135",
            "druid_4_149",
            "druid_4_141",
            "druid_4_143",
          ],
          active: false,
          index: 16,
          link: false,
          image: "/paragon/barbarian/ResistanceAll_active.png",
          bg: "magic",
        },
        {
          id: "druid_4_143",
          activable_ids: ["druid_4_136", "druid_4_150", "druid_4_142"],
          active: false,
          index: 17,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          bg: "magic",
        },
      ],
      [
        {
          id: "druid_4_144",
          activable_ids: ["druid_4_137", "druid_4_151", "druid_4_145"],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_145",
          activable_ids: ["druid_4_138", "druid_4_144"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_146",
          activable_ids: ["druid_4_140", "druid_4_153", "druid_4_147"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_147",
          activable_ids: ["druid_4_146", "druid_4_148"],
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_148",
          activable_ids: ["druid_4_141", "druid_4_147", "druid_4_149"],
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/ResistanceAll_active.png",
          bg: "magic",
        },
        {
          id: "druid_4_149",
          activable_ids: ["druid_4_142", "druid_4_148", "druid_4_150"],
          active: false,
          index: 16,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          bg: "magic",
        },
        {
          id: "druid_4_150",
          activable_ids: ["druid_4_143", "druid_4_149"],
          active: false,
          index: 17,
          link: false,
          image: "/paragon/barbarian/ResistanceAll_active.png",
          bg: "rare",
        },
      ],
      [
        {
          id: "druid_4_151",
          activable_ids: ["druid_4_144", "druid_4_154"],
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          label: "Nœud normal",
          options: ["+5 volonte"],
        },
        {
          id: "druid_4_152",
          activable_ids: ["druid_4_156", "druid_4_153"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_153",
          activable_ids: ["druid_4_146", "druid_4_157", "druid_4_152"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
      ],
      [
        {
          id: "druid_4_154",
          active: false,
          opened: true,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
        {
          id: "druid_4_155",
          activable_ids: ["druid_4_154", "druid_4_156"],
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["+5 Force"],
        },
        {
          id: "druid_4_156",
          activable_ids: ["druid_4_152", "druid_4_155", "druid_4_157"],
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          label: "Nœud normal",
          options: ["5 Dextérité"],
        },
        {
          id: "druid_4_157",
          activable_ids: ["druid_4_153", "druid_4_156"],
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          label: "Nœud normal",
          options: ["5 Intelligence"],
        },
      ],
      [
        {
          id: "druid_4_158",
          active: false,
          index: 10,
          direction: "bottom",
          link: true,
          image: "/paragon/barbarian/Gate_active.png",
          label: "Porte de fixation de la carte",
          options: ["5 Force", "5 Intelligence", "5 Volonté", "5 Dextérité"],
        },
      ],
    ],
  },