glyph_ids: [1,2,8,11,14,20,23],int
glyph_ids: [5,7,12,13,15,16,17,18,19],dex
glyph_ids: [3,4,6,9,10,21,22],will


{
          id: "druid_2_38",
          active: null,
          index: 5,
          link: true,
          image: "/paragon/tile_bg_glyph.png",
          is_icon: true,
        },



        [
        {
          id: "druid_2_1",
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_4"],
        },
        {
          id: "druid_2_2",
          active: false,
          index: 10,
          link: true,
          direction: "top",
          image: "/paragon/barbarian/Gate_active.png",
        },
      ],
      [
        {
          id: "druid_2_3",
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: ["druid_2_12", "druid_2_4"],
        },
        {
          id: "druid_2_4",
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_1", "druid_2_13", "druid_2_3", "druid_2_5"],
        },
        {
          id: "druid_2_5",
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_14", "druid_2_4", "druid_2_6"],
        },
        {
          id: "druid_2_6",
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_5", "druid_2_7"],
        },
        {
          id: "druid_2_7",
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_6", "druid_2_8"],
        },
        {
          id: "druid_2_8",
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_7", "druid_2_9"],
        },
        {
          id: "druid_2_9",
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          opened: true,
        },
        {
          id: "druid_2_10",
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_16", "druid_2_9"],
        },
      ],
      [
        {
          id: "druid_2_11",
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_12"],
        },
        {
          id: "druid_2_12",
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["5 Force"],
          activable_ids: [
            "druid_2_3",
            "druid_2_18",
            "druid_2_11",
            "druid_2_13",
          ],
        },
        {
          id: "druid_2_13",
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: [
            "druid_2_4",
            "druid_2_19",
            "druid_2_12",
            "druid_2_14",
          ],
        },
        {
          id: "druid_2_14",
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: ["druid_2_5", "druid_2_20", "druid_2_13"],
        },
        {
          id: "druid_2_15",
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_9", "druid_2_23", "druid_2_16"],
        },
        {
          id: "druid_2_16",
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: ["druid_2_10", "druid_2_24", "druid_2_15"],
        },
      ],
      [
        {
          id: "druid_2_17",
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_26"],
        },
        {
          id: "druid_2_18",
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: ["druid_2_12", "druid_2_19"],
        },
        {
          id: "druid_2_19",
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: [
            "druid_2_13",
            "druid_2_28",
            "druid_2_18",
            "druid_2_20",
          ],
        },
        {
          id: "druid_2_20",
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/DamageCore_active.png",
          activable_ids: [
            "druid_2_14",
            "druid_2_29",
            "druid_2_19",
            "druid_2_21",
          ],
        },
        {
          id: "druid_2_21",
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/DamageCore_active.png",
          activable_ids: ["druid_2_30", "druid_2_20", "druid_2_22"],
        },
        {
          id: "druid_2_22",
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: ["druid_2_31", "druid_2_21"],
        },
        {
          id: "druid_2_23",
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_15", "druid_2_24"],
        },
        {
          id: "druid_2_24",
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["5 Force"],
          activable_ids: ["druid_2_16", "druid_2_32", "druid_2_23"],
        },
      ],
      [
        {
          id: "druid_2_25",
          active: false,
          index: 1,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_34", "druid_2_26"],
        },
        {
          id: "druid_2_26",
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: [
            "druid_2_17",
            "druid_2_35",
            "druid_2_25",
            "druid_2_27",
          ],
        },
        {
          id: "druid_2_27",
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_36", "druid_2_26"],
        },
        {
          id: "druid_2_28",
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_19", "druid_2_38", "druid_2_29"],
        },
        {
          id: "druid_2_29",
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: [
            "druid_2_20",
            "druid_2_39",
            "druid_2_28",
            "druid_2_30",
          ],
        },
        {
          id: "druid_2_30",
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/DamageCore_active.png",
          activable_ids: [
            "druid_2_21",
            "druid_2_40",
            "druid_2_29",
            "druid_2_31",
          ],
        },
        {
          id: "druid_2_31",
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/DamageCore_active.png",
          activable_ids: ["druid_2_22", "druid_2_41", "druid_2_30"],
        },
        {
          id: "druid_2_32",
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_24"],
        },
      ],
      [
        {
          id: "druid_2_33",
          active: false,
          index: 0,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_34"],
        },
        {
          id: "druid_2_34",
          active: false,
          index: 1,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: [
            "druid_2_25",
            "druid_2_45",
            "druid_2_33",
            "druid_2_35",
          ],
        },
        {
          id: "druid_2_35",
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: [
            "druid_2_26",
            "druid_2_46",
            "druid_2_34",
            "druid_2_36",
          ],
        },
        {
          id: "druid_2_36",
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: [
            "druid_2_27",
            "druid_2_47",
            "druid_2_35",
            "druid_2_37",
          ],
        },
        {
          id: "druid_2_37",
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: ["druid_2_48", "druid_2_36", "druid_2_38"],
        },
        {
          id: "druid_2_38",
          active: null,
          index: 5,
          link: true,
          image: "/paragon/tile_bg_glyph.png",
          is_icon: true,
        },
        {
          id: "druid_2_39",
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_29", "druid_2_38", "druid_2_40"],
        },
        {
          id: "druid_2_40",
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: [
            "druid_2_30",
            "druid_2_50",
            "druid_2_39",
            "druid_2_41",
          ],
        },
        {
          id: "druid_2_41",
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: [
            "druid_2_31",
            "druid_2_51",
            "druid_2_40",
            "druid_2_42",
          ],
        },
        {
          id: "druid_2_42",
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_52", "druid_2_41", "druid_2_43"],
        },
        {
          id: "druid_2_43",
          active: false,
          index: 10,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_42"],
        },
        {
          id: "druid_2_44",
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_53"],
        },
      ],
      [
        {
          id: "druid_2_45",
          active: false,
          index: 1,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["5 Force"],
          activable_ids: ["druid_2_34", "druid_2_54", "druid_2_46"],
        },
        {
          id: "druid_2_46",
          active: false,
          index: 2,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_35", "druid_2_45", "druid_2_47"],
        },
        {
          id: "druid_2_47",
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          activable_ids: [
            "druid_2_36",
            "druid_2_55",
            "druid_2_46",
            "druid_2_48",
          ],
        },
        {
          id: "druid_2_48",
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["5 Force"],
          activable_ids: [
            "druid_2_37",
            "druid_2_56",
            "druid_2_47",
            "druid_2_49",
          ],
        },
        {
          id: "druid_2_49",
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_38", "druid_2_57", "druid_2_48"],
        },
        {
          id: "druid_2_50",
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_40", "druid_2_51"],
        },
        {
          id: "druid_2_51",
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: [
            "druid_2_41",
            "druid_2_59",
            "druid_2_50",
            "druid_2_52",
          ],
        },
        {
          id: "druid_2_52",
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Str_active.png",
          label: "Nœud normal",
          options: ["5 Force"],
          activable_ids: ["druid_2_42", "druid_2_60", "druid_2_51"],
        },
        {
          id: "druid_2_53",
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/ResourceUp_active.png",
          activable_ids: ["druid_2_44", "druid_2_62"],
        },
      ],
      [
        {
          id: "druid_2_54",
          active: false,
          index: 1,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_45", "druid_2_63"],
        },
        {
          id: "druid_2_55",
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          activable_ids: ["druid_2_47", "druid_2_64", "druid_2_56"],
        },
        {
          id: "druid_2_56",
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          activable_ids: [
            "druid_2_48",
            "druid_2_65",
            "druid_2_55",
            "druid_2_57",
          ],
        },
        {
          id: "druid_2_57",
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: [
            "druid_2_49",
            "druid_2_66",
            "druid_2_56",
            "druid_2_58",
          ],
        },
        {
          id: "druid_2_58",
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_67", "druid_2_57"],
        },
        {
          id: "druid_2_59",
          active: false,
          index: 8,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: ["druid_2_51", "druid_2_60"],
        },
        {
          id: "druid_2_60",
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_52", "druid_2_69", "druid_2_59"],
        },
        {
          id: "druid_2_61",
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/Spirit_active.png",
          activable_ids: ["druid_2_70", "druid_2_62"],
        },
        {
          id: "druid_2_62",
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          activable_ids: ["druid_2_53", "druid_2_71", "druid_2_61"],
        },
      ],
      [
        {
          id: "druid_2_63",
          active: false,
          index: 1,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_54", "druid_2_79"],
        },
        {
          id: "druid_2_64",
          active: false,
          index: 3,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_55", "druid_2_65"],
        },
        {
          id: "druid_2_65",
          active: false,
          index: 4,
          link: false,
          image: "/paragon/barbarian/Damage_active.png",
          activable_ids: ["druid_2_56", "druid_2_64", "druid_2_66"],
        },
        {
          id: "druid_2_66",
          active: false,
          index: 5,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: [
            "druid_2_57",
            "druid_2_80",
            "druid_2_65",
            "druid_2_67",
          ],
        },
        {
          id: "druid_2_67",
          active: false,
          index: 6,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: [
            "druid_2_58",
            "druid_2_81",
            "druid_2_66",
            "druid_2_68",
          ],
        },
        {
          id: "druid_2_68",
          active: false,
          index: 7,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_82", "druid_2_67"],
        },
        {
          id: "druid_2_69",
          active: false,
          index: 9,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_60", "druid_2_84"],
        },
        {
          id: "druid_2_70",
          active: false,
          index: 11,
          link: false,
          image: "/paragon/barbarian/ResourceUp_active.png",
          activable_ids: ["druid_2_61", "druid_2_86", "druid_2_71"],
        },
        {
          id: "druid_2_71",
          active: false,
          index: 12,
          link: false,
          image: "/paragon/barbarian/ResourceUp_active.png",
          activable_ids: ["druid_2_62", "druid_2_70", "druid_2_72"],
        },
        {
          id: "druid_2_72",
          active: false,
          index: 13,
          link: false,
          image: "/paragon/barbarian/HPPercent_active.png",
          activable_ids: ["druid_2_71", "druid_2_73"],
        },
        {
          id: "druid_2_73",
          active: false,
          index: 14,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_87", "druid_2_72", "druid_2_74"],
        },
        {
          id: "druid_2_74",
          active: false,
          index: 15,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_88", "druid_2_73", "druid_2_75"],
        },
        {
          id: "druid_2_75",
          active: false,
          index: 16,
          link: false,
          image: "/paragon/barbarian/Int_active.png",
          glyph_ids: [1,2,8,11,14,20,23],
          label: "Nœud normal",
          options: ["5 Intelligence"],
          activable_ids: ["druid_2_89", "druid_2_74", "druid_2_76"],
        },
        {
          id: "druid_2_76",
          active: false,
          index: 17,
          link: false,
          image: "/paragon/barbarian/Will_active.png",
          glyph_ids: [3,4,6,9,10,21,22],
          label: "Nœud normal",
          options: ["+5 Volonté"],
          activable_ids: ["druid_2_75", "druid_2_77"],
        },
        {
          id: "druid_2_77",
          active: false,
          index: 18,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: ["druid_2_90", "druid_2_76", "druid_2_78"],
        },
        {
          id: "druid_2_78",
          active: false,
          index: 19,
          link: false,
          image: "/paragon/barbarian/Dex_active.png",
          glyph_ids: [5,7,12,13,15,16,17,18,19],
          label: "Nœud normal",
          options: ["5 Dextérité"],
          activable_ids: ["druid_2_91", "druid_2_77"],
        },
      ],